package com.ampairs.auth.model.dto

import com.fasterxml.jackson.annotation.JsonProperty
import jakarta.validation.constraints.NotEmpty
import jakarta.validation.constraints.NotNull

class AuthInitRequest {
    @NotNull
    @JsonProperty("country_code")
    var countryCode = 91

    @NotNull
    @NotEmpty
    var phone: String = ""

    @JsonProperty("token_id")
    var tokenId: String = ""

    @JsonProperty("recaptcha_token")
    var recaptchaToken: String? = null

    @JsonProperty("device_id")
    var deviceId: String? = null // For mobile apps, generated by client; for web, will be generated server-side

    @JsonProperty("device_name")
    var deviceName: String? = null // e.g., "iPhone 15", "John's MacBook"

    fun phoneNumber(): String {
        return this.countryCode.toString() + this.phone
    }
}
