package com.ampairs.auth.model.dto

import com.fasterxml.jackson.annotation.JsonProperty
import jakarta.validation.constraints.NotEmpty
import jakarta.validation.constraints.NotNull


data class AuthInitRequest(

    @field:NotNull
    @JsonProperty("country_code")
    val countryCode: Int = 91,

    @field:NotNull
    @field:NotEmpty
    val phone: String = "",

    @JsonProperty("recaptcha_token")
    val recaptchaToken: String? = null,

    @JsonProperty("device_id")
    val deviceId: String? = null, // For mobile apps, generated by client; for web, will be generated server-side

    @JsonProperty("device_name")
    val deviceName: String? = null, // e.g., "iPhone 15", "John's MacBook"

    @JsonProperty("device_type")
    val deviceType: String? = null, // "Mobile", "Tablet", "Desktop"

    @JsonProperty("platform")
    val platform: String? = null, // "iOS", "Android", "Windows", "macOS", "Linux"

    @JsonProperty("browser")
    val browser: String? = null, // "Google Chrome", "Safari", "Firefox", etc.

    @JsonProperty("os")
    val os: String? = null, // "iOS 17.1", "Android 14", "Windows 11", etc.

) {
    fun phoneNumber(): String = "$countryCode$phone"
}

