-- cb_maintenance Module Migration (PostgreSQL)
-- Version: 1.0.131
-- Description: maintenance — ticket classification catalog (Department › Category › Sub-category).
--              Global reference data (not tenant-scoped): one shared taxonomy, pull-only sync.
-- Dependencies: V1.0.130 (cb_maintenance base tables)

CREATE TABLE ticket_bucket (
    id BIGSERIAL PRIMARY KEY,
    uid VARCHAR(200) NOT NULL UNIQUE,
    department VARCHAR(100) NOT NULL,
    category VARCHAR(150) NOT NULL,
    sub_category_1 VARCHAR(200) NOT NULL,
    sub_category_2 VARCHAR(200) NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cb_ticket_bucket_dept ON ticket_bucket(department);
CREATE UNIQUE INDEX uk_cb_ticket_bucket ON ticket_bucket(department, category, sub_category_1, sub_category_2);

-- Seed the standard maintenance ticket taxonomy (830 rows).
INSERT INTO ticket_bucket (uid, department, category, sub_category_1, sub_category_2) VALUES
('TKB000001','IT & Software','AgaveSoftware','Slow',''),
('TKB000002','IT & Software','AgaveSoftware','Wrong BOM',''),
('TKB000003','IT & Software','AgaveSoftware','Wrong Sales',''),
('TKB000004','IT & Software','Biometric','Display Issue',''),
('TKB000005','IT & Software','Biometric','Network',''),
('TKB000006','IT & Software','Biometric','Scanning Issue',''),
('TKB000007','IT & Software','CCTV','Add A Camera',''),
('TKB000008','IT & Software','CCTV','Backup issue',''),
('TKB000009','IT & Software','CCTV','Camera not working',''),
('TKB000010','IT & Software','CCTV','Clean Cameras',''),
('TKB000011','IT & Software','CCTV','Not able to view on phone',''),
('TKB000012','IT & Software','CCTV','Shift Location',''),
('TKB000013','IT & Software','EDCMachine','Adapter issue',''),
('TKB000014','IT & Software','EDCMachine','Error Message',''),
('TKB000015','IT & Software','EDCMachine','Integration Failed',''),
('TKB000016','IT & Software','EDCMachine','Internet',''),
('TKB000017','IT & Software','EDCMachine','Not turning on',''),
('TKB000018','IT & Software','EDCMachine','Settlement issue',''),
('TKB000019','IT & Software','Internet','Connectivity issue',''),
('TKB000020','IT & Software','Internet','Internet Slow',''),
('TKB000021','IT & Software','Internet','New Requirement',''),
('TKB000022','IT & Software','Internet','Wifi Not Working',''),
('TKB000023','IT & Software','Internet','WLAN Not working',''),
('TKB000024','IT & Software','Keyboard','Broken',''),
('TKB000025','IT & Software','Keyboard','Keys not working',''),
('TKB000026','IT & Software','Label/StickerPrinter','Adapter issue',''),
('TKB000027','IT & Software','Label/StickerPrinter','Cable',''),
('TKB000028','IT & Software','Label/StickerPrinter','Configuaration',''),
('TKB000029','IT & Software','Label/StickerPrinter','New Requirement',''),
('TKB000030','IT & Software','Label/StickerPrinter','Not getting on',''),
('TKB000031','IT & Software','Label/StickerPrinter','Printing Not Clear',''),
('TKB000032','IT & Software','Label/StickerPrinter','Wrong Print',''),
('TKB000033','IT & Software','Mouse','Not Functioning',''),
('TKB000034','IT & Software','Mouse','Not getting on',''),
('TKB000035','IT & Software','Phone/Telephone','No Network',''),
('TKB000036','IT & Software','Phone/Telephone','Not audible',''),
('TKB000037','IT & Software','Phone/Telephone','Not getting Charging',''),
('TKB000038','IT & Software','Phone/Telephone','Not getting on',''),
('TKB000039','IT & Software','POS/Desktop','Internet',''),
('TKB000040','IT & Software','POS/Desktop','Not getting on',''),
('TKB000041','IT & Software','POS/Desktop','Not loading - Windows/OS',''),
('TKB000042','IT & Software','POS/Desktop','Order - Speaker issue',''),
('TKB000043','IT & Software','POS/Desktop','Software Problem',''),
('TKB000044','IT & Software','POS/Desktop','System is Slow',''),
('TKB000045','IT & Software','POS/Desktop','WLAN Cable',''),
('TKB000046','IT & Software','Prime/UrbanPiper','Product Image issue',''),
('TKB000047','IT & Software','Prime/UrbanPiper','Price Related',''),
('TKB000048','IT & Software','Prime/UrbanPiper','Prime access',''),
('TKB000049','IT & Software','ReceiptPrinter','Adapter issue',''),
('TKB000050','IT & Software','ReceiptPrinter','Cable',''),
('TKB000051','IT & Software','ReceiptPrinter','Configuaration',''),
('TKB000052','IT & Software','ReceiptPrinter','New Requirement',''),
('TKB000053','IT & Software','ReceiptPrinter','Not getting on',''),
('TKB000054','IT & Software','ReceiptPrinter','Printing Not Clear',''),
('TKB000055','IT & Software','ReceiptPrinter','Wrong Print',''),
('TKB000056','Marketing','Marketing Maintenance','Directional signage','Damaged'),
('TKB000057','Marketing','Marketing Maintenance','Directional signage','Updated'),
('TKB000058','Marketing','Marketing Maintenance','Façade Sticker','Damaged'),
('TKB000059','Marketing','Marketing Maintenance','Façade Sticker','Updated'),
('TKB000060','Marketing','Marketing Maintenance','Frame/ lightbox','Damaged'),
('TKB000061','Marketing','Marketing Maintenance','Frame/ lightbox','Updated'),
('TKB000062','Marketing','Marketing Maintenance','Gate Arch','Damaged'),
('TKB000063','Marketing','Marketing Maintenance','Gate Arch','Updated'),
('TKB000064','Marketing','Marketing Maintenance','Menu board','Damaged'),
('TKB000065','Marketing','Marketing Maintenance','Menu board','Updated'),
('TKB000066','Marketing','Marketing Maintenance','Poster','Damaged'),
('TKB000067','Marketing','Marketing Maintenance','Poster','Updated'),
('TKB000068','Marketing','Marketing Maintenance','Standee','Damaged'),
('TKB000069','Marketing','Marketing Maintenance','Standee','Updated'),
('TKB000070','Marketing','Printwork','Backlit',''),
('TKB000071','Marketing','Printwork','Coupons',''),
('TKB000072','Marketing','Printwork','Digital screens/ TV slides',''),
('TKB000073','Marketing','Printwork','Facade stickers/ glass stickers',''),
('TKB000074','Marketing','Printwork','Flyers',''),
('TKB000075','Marketing','Printwork','Gate Arch',''),
('TKB000076','Marketing','Printwork','Menu inserts',''),
('TKB000077','Marketing','Printwork','Outdoor banners',''),
('TKB000078','Marketing','Printwork','Posters',''),
('TKB000079','Marketing','Printwork','Standee',''),
('TKB000080','Marketing','Printwork','Tent cards',''),
('TKB000081','Spare Parts','2 Door Chiller Celfrost','2DC01CF Gasket',''),
('TKB000082','Spare Parts','2 Door Chiller Celfrost','2DC02CF FAN MOTOR - Evoporator',''),
('TKB000083','Spare Parts','2 Door Chiller Celfrost','2DC03CF CONTROLLER',''),
('TKB000084','Spare Parts','2 Door Chiller Celfrost','2DC04CF Hinges - Door',''),
('TKB000085','Spare Parts','2 Door Chiller Celfrost','2DC05CF Fan motor - Condensor',''),
('TKB000086','Spare Parts','2 Door Chiller Celfrost','2DC06CF Q Motor',''),
('TKB000087','Spare Parts','2 Door Chiller Trufrost','2DC01TF Gasket',''),
('TKB000088','Spare Parts','2 Door Chiller Trufrost','2DC02TF FAN MOTOR - Evoporator',''),
('TKB000089','Spare Parts','2 Door Chiller Trufrost','2DC03TF CONTROLLER',''),
('TKB000090','Spare Parts','2 Door Chiller Trufrost','2DC04TF Hinges - Door',''),
('TKB000091','Spare Parts','2 Door Freezer Celfrost','2DF01CF Gasket',''),
('TKB000092','Spare Parts','2 Door Freezer Celfrost','2DF02CF FAN MOTOR - Evoporator',''),
('TKB000093','Spare Parts','2 Door Freezer Celfrost','2DF03CF CONTROLLER',''),
('TKB000094','Spare Parts','2 Door Freezer Celfrost','2DF04CF Hinges - Door',''),
('TKB000095','Spare Parts','2 Door Freezer Celfrost','2DF05CF Fan motor - Condensor',''),
('TKB000096','Spare Parts','2 Door Freezer Celfrost','2DF06CF Q Motor',''),
('TKB000097','Spare Parts','2 Range Gas Burner Artikel Inox','2GB01AI Gas burner',''),
('TKB000098','Spare Parts','2 Range Gas Burner Artikel Inox','2GB02AIR Gas valve - NCV Red',''),
('TKB000099','Spare Parts','2 Range Gas Burner Artikel Inox','2GB02AIB Gas valve - NCV Black',''),
('TKB000100','Spare Parts','2 Range Gas Burner Artikel Inox','2GB03AI Leg Bushes',''),
('TKB000101','Spare Parts','2 Range Gas Burner Artikel Inox','2GB04AI Copper pipe',''),
('TKB000102','Spare Parts','2 Range Gas Burner Artikel Inox','2GB05AI Gas pipe',''),
('TKB000103','Spare Parts','2 Range Gas Burner Artikel Inox','2GB06AI Top holder - Burnr grid',''),
('TKB000104','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB01SKS Gas burner - Small',''),
('TKB000105','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB01SKB Gas burner - Big',''),
('TKB000106','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB02SK Gas valve',''),
('TKB000107','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB03SK Leg Bushes - Metal bushes',''),
('TKB000108','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB04SK Copper pipe',''),
('TKB000109','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB05SK Gas pipe - Hydraulic',''),
('TKB000110','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB06SK Pilot',''),
('TKB000111','Spare Parts','2 Range Gas Burner Spire Kitchen Solutions','2GB07SK Burner Grid',''),
('TKB000112','Spare Parts','3 Door Chiller Trufrost','3DC01TF Fan motor - Condensor',''),
('TKB000113','Spare Parts','4 Door Chiller Celfrost','4DC01CF Gasket',''),
('TKB000114','Spare Parts','4 Door Chiller Celfrost','4DC02CF FAN MOTOR - Evoporator',''),
('TKB000115','Spare Parts','4 Door Chiller Celfrost','4DC03CF CONTROLLER',''),
('TKB000116','Spare Parts','4 Door Chiller Celfrost','4DC04CF Hinges - Door',''),
('TKB000117','Spare Parts','4 Door Chiller Celfrost','4DC05CF Fan motor - Condensor',''),
('TKB000118','Spare Parts','4 Door Chiller Celfrost','4DC06CF Q Motor',''),
('TKB000119','Spare Parts','4 Door Chiller Trufrost','4DC01TF Gasket',''),
('TKB000120','Spare Parts','4 Door Chiller Trufrost','4DC02TF FAN MOTOR - Evoporator',''),
('TKB000121','Spare Parts','4 Door Chiller Trufrost','4DC03TF CONTROLLER',''),
('TKB000122','Spare Parts','4 Door Chiller Trufrost','4DC04TF Hinges - Door',''),
('TKB000123','Spare Parts','4 Door Chiller Trufrost','4DC05TF Fan motor - Condensor',''),
('TKB000124','Spare Parts','4 Door Freezer Celfrost','4DF01CF Gasket',''),
('TKB000125','Spare Parts','4 Door Freezer Celfrost','4DF02CF Dixel & Subzero controller',''),
('TKB000126','Spare Parts','4 Door Freezer Celfrost','4DF03CFLL Door hinge left lower',''),
('TKB000127','Spare Parts','4 Door Freezer Celfrost','4DF03CFLU Door hinge left upper',''),
('TKB000128','Spare Parts','4 Door Freezer Celfrost','4DF03CFRL Door hinge right lower',''),
('TKB000129','Spare Parts','4 Door Freezer Celfrost','4DF03CFRU Door hinge right upper',''),
('TKB000130','Spare Parts','4 Door Freezer Celfrost','4DF04CF Cooling fan motor',''),
('TKB000131','Spare Parts','4 Door Freezer Celfrost','4DF05CF Condensor fan motor',''),
('TKB000132','Spare Parts','4 Door Freezer Celfrost','4DF06CF Heater',''),
('TKB000133','Spare Parts','4 Door Freezer Celfrost','4DF07CF Relay',''),
('TKB000134','Spare Parts','4 Door Freezer Celfrost','4DF08CF Q Motor',''),
('TKB000135','Spare Parts','4 Door Freezer Trufrost','4DF01TF Gasket',''),
('TKB000136','Spare Parts','4 Door Freezer Trufrost','4DF02TF FAN MOTOR - Evoporator',''),
('TKB000137','Spare Parts','4 Door Freezer Trufrost','4DF03TF CONTROLLER',''),
('TKB000138','Spare Parts','4 Door Freezer Trufrost','4DF04TF Hinges - Door',''),
('TKB000139','Spare Parts','4 Door Freezer Trufrost','4DF05TF Fan motor - Condensor',''),
('TKB000140','Spare Parts','AHU Sna Aircon','AHU01SNA Blower',''),
('TKB000141','Spare Parts','AHU Sna Aircon','AHU02SNA Shaft',''),
('TKB000142','Spare Parts','AHU Sna Aircon','AHU03SNA V belt',''),
('TKB000143','Spare Parts','AHU Sna Aircon','AHU04SNA Cooling coil',''),
('TKB000144','Spare Parts','AHU Sna Aircon','AHU05SNA Fine filter',''),
('TKB000145','Spare Parts','AHU Sna Aircon','AHU06SNA Door handle',''),
('TKB000146','Spare Parts','AHU Sna Aircon','AHU07SNA Door lock',''),
('TKB000147','Spare Parts','AHU Sna Aircon','AHU08SNA Grease',''),
('TKB000148','Spare Parts','Aircurtain Euronics','AC01EU Blower',''),
('TKB000149','Spare Parts','Aircurtain Euronics','AC02EU Blower moter',''),
('TKB000150','Spare Parts','Aircurtain Euronics','AC03EU Sensor',''),
('TKB000151','Spare Parts','Aircurtain Euronics','AC04EU Magnetic Sensor',''),
('TKB000152','Spare Parts','Aircurtain Mitzvah','AC01MT Blower',''),
('TKB000153','Spare Parts','Aircurtain Mitzvah','AC02MT Blower moter - single shaft',''),
('TKB000154','Spare Parts','Aircurtain Mitzvah','AC03MT Blower moter - double shaft',''),
('TKB000155','Spare Parts','Aircurtain Mitzvah','AC04MT Sensor Controller - single swtich',''),
('TKB000156','Spare Parts','Aircurtain Mitzvah','AC05MT Sensor Controller - double switch',''),
('TKB000157','Spare Parts','Back Bar Celfrost','BB01CF gasket',''),
('TKB000158','Spare Parts','Back Bar Celfrost','BB02CF lights',''),
('TKB000159','Spare Parts','Back Bar Celfrost','BB03CFL Left Door',''),
('TKB000160','Spare Parts','Back Bar Celfrost','BB03CFR Right Door',''),
('TKB000161','Spare Parts','Back Bar Celfrost','BB04CF Cooling Coil',''),
('TKB000162','Spare Parts','Back Bar Celfrost','BB05CF Temp controller',''),
('TKB000163','Spare Parts','Back Bar Celfrost','BB06CF Q Motor',''),
('TKB000164','Spare Parts','Back Bar Celfrost','BB07CF Door Spring',''),
('TKB000165','Spare Parts','Back Bar Celfrost','BB08CF Excel Fan Motor 4x4"',''),
('TKB000166','Spare Parts','Back Bar Trufrost','BB01TF gasket',''),
('TKB000167','Spare Parts','Back Bar Trufrost','BB02TF lights',''),
('TKB000168','Spare Parts','Chair Bushes Ss Fabrication','CB01 Chair Bushes ( 12mm Rod Bush Black colour )',''),
('TKB000169','Spare Parts','Chest Freezer Celfrost','CF01CF Gasket',''),
('TKB000170','Spare Parts','Chest Freezer Celfrost','CF02CF Door handle',''),
('TKB000171','Spare Parts','Chest Freezer Celfrost','CF03CF Door hing',''),
('TKB000172','Spare Parts','Chest Freezer Celfrost','CF04CF Condensing grill',''),
('TKB000173','Spare Parts','Chest Freezer Celfrost','CF05CF Condensing fan',''),
('TKB000174','Spare Parts','Chest Freezer Celfrost','CF06CF Condensor motor',''),
('TKB000175','Spare Parts','Chest Freezer Celfrost','CF07CF Relay',''),
('TKB000176','Spare Parts','Chest Freezer Celfrost','CF08CF Q Motor',''),
('TKB000177','Spare Parts','Cold Line Artikel Inox','CL01AI Door Gasket',''),
('TKB000178','Spare Parts','Cold Line Artikel Inox','CL02AI Temperature controller',''),
('TKB000179','Spare Parts','Cold Line Artikel Inox','CL03AI Condenser Fan',''),
('TKB000180','Spare Parts','Cold Line Artikel Inox','CL04AI Evoporator Fan - 4 Inch',''),
('TKB000181','Spare Parts','Cold Line Artikel Inox','CL05AI Hinges - Door',''),
('TKB000182','Spare Parts','Cold Line Artikel Inox','CL06AI Leg Bushes - Coldline',''),
('TKB000183','Spare Parts','Cold Line Spire Kitchen Solutions','CL01SK Door Gasket - screwed type',''),
('TKB000184','Spare Parts','Cold Line Spire Kitchen Solutions','CL02SK Door Spring',''),
('TKB000185','Spare Parts','Cold Line Spire Kitchen Solutions','CL03SK Condensor fan',''),
('TKB000186','Spare Parts','Cold Line Spire Kitchen Solutions','CL04SK Condensor motor',''),
('TKB000187','Spare Parts','Cold Line Spire Kitchen Solutions','CL05SK 4 Inch Cooling fans',''),
('TKB000188','Spare Parts','Cold Line Spire Kitchen Solutions','CL06SK Temperature Controller - Dixel - XROCX',''),
('TKB000189','Spare Parts','Cold Line Spire Kitchen Solutions','CL07SK Rocker Switch',''),
('TKB000190','Spare Parts','Cold Room Bluestar','CR01BS Controller',''),
('TKB000191','Spare Parts','Cold Room Bluestar','CR02BS Gasket - 4 Mtr',''),
('TKB000192','Spare Parts','Cold Room Bluestar','CR03BS Sweep gasket',''),
('TKB000193','Spare Parts','Cold Room Bluestar','CR04BS Hinges - Door bottom',''),
('TKB000194','Spare Parts','Cold Room Bluestar','CR05BS Hinges - Door top',''),
('TKB000195','Spare Parts','Cold Room Bluestar','CR06BS Handle',''),
('TKB000196','Spare Parts','Cold Room Bluestar','CR07BS Door closer',''),
('TKB000197','Spare Parts','Cold Room Bluestar','CR08BS Tubelight 2 ft',''),
('TKB000198','Spare Parts','Cold Room Bluestar','CR09BS Cooling fan motor',''),
('TKB000199','Spare Parts','Cold Room Odu Bluestar','CRODU01BS Condensor fan',''),
('TKB000200','Spare Parts','Cold Room Odu Bluestar','CRODU02BS Condendor motor','');

INSERT INTO ticket_bucket (uid, department, category, sub_category_1, sub_category_2) VALUES
('TKB000201','Spare Parts','Cold Room Odu Bluestar','CRODU03BS Capacitor',''),
('TKB000202','Spare Parts','Cold Room SLB','CR01SLB Strip Curtain',''),
('TKB000203','Spare Parts','Cold Room SLB','CR02SLB Curtain stand - SS',''),
('TKB000204','Spare Parts','DB L&T','DB01LT 15A 3 Phase motor starter',''),
('TKB000205','Spare Parts','DB Legrand','DB01L 16 A SP MCB',''),
('TKB000206','Spare Parts','DB Legrand','DB02L 32 A SP MCB',''),
('TKB000207','Spare Parts','DB Legrand','DB03L 32A DP MCB',''),
('TKB000208','Spare Parts','DB Legrand','DB04L 32A DP RCCB',''),
('TKB000209','Spare Parts','DB Legrand','DB05L 63A 4P MCB',''),
('TKB000210','Spare Parts','DB Legrand','DB06L 16 A DP RCCB',''),
('TKB000211','Spare Parts','DB Legrand','DB07L 32A DP RCCB',''),
('TKB000212','Spare Parts','DB Legrand','DB08L 10A 4P MCB',''),
('TKB000213','Spare Parts','DB Legrand','DB09L 25A 4P MCB',''),
('TKB000214','Spare Parts','DB Minilac','DB01ML Single Phase preventer',''),
('TKB000215','Spare Parts','DB Sna Aircon','DB01SNA Starter for Exhaust',''),
('TKB000216','Spare Parts','DB Sna Aircon','DB02SNA Starter for Fresh Air',''),
('TKB000217','Spare Parts','DG Cummins','DG01 Coolent',''),
('TKB000218','Spare Parts','DG Cummins','DG02 Battery Distilled water',''),
('TKB000219','Spare Parts','Dsw Ac Commercial Aircon','DSWAC01CA Stainer',''),
('TKB000220','Spare Parts','Dsw Ac Commercial Aircon','DSWAC02CA Condensor',''),
('TKB000221','Spare Parts','Dsw Ac Commercial Aircon','DSWAC03CA Valve',''),
('TKB000222','Spare Parts','Dsw Ac Commercial Aircon','DSWAC04CA Cooling coil',''),
('TKB000223','Spare Parts','Dsw Ac Commercial Aircon','DSWAC05CA Blower',''),
('TKB000224','Spare Parts','Dsw Ac Commercial Aircon','DSWAC06CA Blower motor',''),
('TKB000225','Spare Parts','Dsw Ac Commercial Aircon','DSWAC07CA Filter',''),
('TKB000226','Spare Parts','Dsw Ac Commercial Aircon','DSWAC08CA Drain valve',''),
('TKB000227','Spare Parts','Eeletric Cable Polycab','EC01 3 core 4 Sq mm',''),
('TKB000228','Spare Parts','Electric Tawa Artikel Inox','ET01AI Heater',''),
('TKB000229','Spare Parts','Electric Tawa Artikel Inox','ET02AI Thermostat',''),
('TKB000230','Spare Parts','Electric Tawa Butler','ET01TF Heater',''),
('TKB000231','Spare Parts','Electric Tawa Butler','ET02TF Thermostat',''),
('TKB000232','Spare Parts','Exhaust Sna Aircon','EX01SNA Exhaust Motor',''),
('TKB000233','Spare Parts','Exhaust Sna Aircon','EX02SNA Pully',''),
('TKB000234','Spare Parts','Exhaust Sna Aircon','EX03SNA Blower',''),
('TKB000235','Spare Parts','Exhaust Sna Aircon','EX04SNA Shaft',''),
('TKB000236','Spare Parts','Exhaust Sna Aircon','EX05SNA V belt',''),
('TKB000237','Spare Parts','Exhaust Sna Aircon','EX06SNA Scruber - filter',''),
('TKB000238','Spare Parts','Exhaust Sna Aircon','EX07SNA Anti Vibration pad',''),
('TKB000239','Spare Parts','Exhaust Sna Aircon','EX08SNA Door handle',''),
('TKB000240','Spare Parts','Exhaust Sna Aircon','EX09SNA Door lock',''),
('TKB000241','Spare Parts','Exhaust Spire Kitchen Solutions','EX01SK Oil container',''),
('TKB000242','Spare Parts','Exhaust Unit APC','EX01APC Exhaust Unit',''),
('TKB000243','Spare Parts','Exhaust Unit APC','EX02APC Fresh Air unit',''),
('TKB000244','Spare Parts','Fresh Air Sna Aircon','FA01SNA Motor',''),
('TKB000245','Spare Parts','Fresh Air Sna Aircon','FA02SNA Pully',''),
('TKB000246','Spare Parts','Fresh Air Sna Aircon','FA03SNA Blower',''),
('TKB000247','Spare Parts','Fresh Air Sna Aircon','FA04SNA Shaft',''),
('TKB000248','Spare Parts','Fresh Air Sna Aircon','FA05SNA V belt',''),
('TKB000249','Spare Parts','Fresh Air Sna Aircon','FA06SNA Fine filter',''),
('TKB000250','Spare Parts','Fresh Air Sna Aircon','FA07SNA Water pump',''),
('TKB000251','Spare Parts','Fresh Air Sna Aircon','FA08SNA Drain valve',''),
('TKB000252','Spare Parts','Fresh Air Sna Aircon','FA09SNA Float valve',''),
('TKB000253','Spare Parts','Fresh Air Sna Aircon','FA10SNA Anti Vibration pad',''),
('TKB000254','Spare Parts','Fryer Artikel Inox','FY01AI Controller - I therm - 718e',''),
('TKB000255','Spare Parts','Fryer Artikel Inox','FY02AI Timer - Universal',''),
('TKB000256','Spare Parts','Fryer Artikel Inox','FY03AI Contactor',''),
('TKB000257','Spare Parts','Fryer Artikel Inox','FY04AI Sensor - Thermocouple - J type',''),
('TKB000258','Spare Parts','Fryer Artikel Inox','FY05AI Heating Element - 2KW',''),
('TKB000259','Spare Parts','Fryer Artikel Inox','FY06AI Leg Bushes',''),
('TKB000260','Spare Parts','Fryer Spire Kitchen Solutions','FY01SK Controller - Selec 303',''),
('TKB000261','Spare Parts','Fryer Spire Kitchen Solutions','FY02SK Timer - XT-346 - Selec',''),
('TKB000262','Spare Parts','Fryer Spire Kitchen Solutions','FY03SK Contactor',''),
('TKB000263','Spare Parts','Fryer Spire Kitchen Solutions','FY04SK Sensor',''),
('TKB000264','Spare Parts','Fryer Spire Kitchen Solutions','FY05SK Buzzer',''),
('TKB000265','Spare Parts','Fryer Spire Kitchen Solutions','FY06SK Indicator',''),
('TKB000266','Spare Parts','Fryer Spire Kitchen Solutions','FY07SK Tongle switch',''),
('TKB000267','Spare Parts','Fryer Spire Kitchen Solutions','FY08SK element',''),
('TKB000268','Spare Parts','Fryer Spire Kitchen Solutions','FY09SK False Bottom',''),
('TKB000269','Spare Parts','Gas Fryer Celfrost','GF01CF On Off regulator - NCV',''),
('TKB000270','Spare Parts','Gas Fryer Celfrost','GF02CF Drain valve',''),
('TKB000271','Spare Parts','Gas Fryer Celfrost','GF03CF Thermostate valve',''),
('TKB000272','Spare Parts','Gas Fryer Celfrost','GF04CF Thermopile',''),
('TKB000273','Spare Parts','Gas Fryer Celfrost','GF05CF Pilot',''),
('TKB000274','Spare Parts','Gas Fryer Celfrost','GF06CF Burner',''),
('TKB000275','Spare Parts','Gas Fryer Celfrost','GF07CF Connection pipe -Hydralic pipe',''),
('TKB000276','Spare Parts','Gas Fryer Celfrost','GF08CF High limit swith',''),
('TKB000277','Spare Parts','Gas Fryer Celfrost','GF09CF Gas - PNG valve',''),
('TKB000278','Spare Parts','Gas Fryer Rob-Hot','GF01RH Thermopile',''),
('TKB000279','Spare Parts','Gas Fryer Rob-Hot','GF02RH Gas Valve',''),
('TKB000280','Spare Parts','Gas Fryer Rob-Hot','GF03RH Thermostat',''),
('TKB000281','Spare Parts','Gas Fryer Rob-Hot','GF04RH Fryer basket',''),
('TKB000282','Spare Parts','Gas Fryer Rob-Hot','GF05RH fryer leg',''),
('TKB000283','Spare Parts','Gas Tawa Artikel Inox','GT01AI Tawa burner',''),
('TKB000284','Spare Parts','Gas Tawa Artikel Inox','GT02AI Gas valve',''),
('TKB000285','Spare Parts','Gas Tawa Artikel Inox','GT03AI Leg Bushes',''),
('TKB000286','Spare Parts','Gas Tawa Spire Kitchen Solutions','GT01SK Tawa burner',''),
('TKB000287','Spare Parts','Gas Tawa Spire Kitchen Solutions','GT02SK Gas valve',''),
('TKB000288','Spare Parts','Gas Tawa Spire Kitchen Solutions','GT03SK Leg Bushes',''),
('TKB000289','Spare Parts','Geyser Racold','GY01 Thermostat',''),
('TKB000290','Spare Parts','Geyser Racold','GY02 High limit swith',''),
('TKB000291','Spare Parts','Hot Cabinet Artikel Inox','HC01AI Silicon Gasket - 2 mtr',''),
('TKB000292','Spare Parts','Hot Cabinet Artikel Inox','HC02AI Rubber Gasket - Pre Fabricated',''),
('TKB000293','Spare Parts','Hot Cabinet Artikel Inox','HC03AI Cooling Fan - Metal - 4 Inch',''),
('TKB000294','Spare Parts','Hot Cabinet Artikel Inox','HC04AI Fins Heater',''),
('TKB000295','Spare Parts','Hot Cabinet Artikel Inox','HC05AI Castor Wheels',''),
('TKB000296','Spare Parts','Hot Cabinet Artikel Inox','HC06AI Door Hinges',''),
('TKB000297','Spare Parts','Hot Cabinet Artikel Inox','HC07AI Door Latch',''),
('TKB000298','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC01SK Temperature controller Frame',''),
('TKB000299','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC02SK Dry Fin Heater',''),
('TKB000300','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC03SK Silicon Gasket',''),
('TKB000301','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC04SK Rocker Switch',''),
('TKB000302','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC05SK Castor Wheels',''),
('TKB000303','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC06SK Door Hinges',''),
('TKB000304','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC07SK Door Spring',''),
('TKB000305','Spare Parts','Hot Cabinet Spire Kitchen Solutions','HC08SK Dixel - XROCX',''),
('TKB000306','Spare Parts','Hotline Artikel Inox','HL01AI Heater - 2KW - M type',''),
('TKB000307','Spare Parts','Hotline Artikel Inox','HL02AI T-38 Frame',''),
('TKB000308','Spare Parts','Hotline Artikel Inox','HL03AI Temperature controller',''),
('TKB000309','Spare Parts','Hotline Artikel Inox','HL04AIG Rocker Switch Green',''),
('TKB000310','Spare Parts','Hotline Artikel Inox','HL04AIR Rocker Switch Red',''),
('TKB000311','Spare Parts','Hotline Artikel Inox','HL04AIGS Rocker Switch Green Small',''),
('TKB000312','Spare Parts','Hotline Artikel Inox','HL05AI Float switch',''),
('TKB000313','Spare Parts','Hotline Artikel Inox','HL06AI Ceramic Heater',''),
('TKB000314','Spare Parts','Hotline None','HL01RE Selector switch - 25Amps',''),
('TKB000315','Spare Parts','Hotline None','HL02RE Solar coil heater - 2 KW',''),
('TKB000316','Spare Parts','Hotline None','HL03RE Thermostat - 110c',''),
('TKB000317','Spare Parts','Hotline Spire Kitchen Solutions','HL01SK Drain valve',''),
('TKB000318','Spare Parts','Hotline Spire Kitchen Solutions','HL02SK Selector switch',''),
('TKB000319','Spare Parts','Hotline Spire Kitchen Solutions','HL03SK Thermostat - 30-110C',''),
('TKB000320','Spare Parts','Hotline Spire Kitchen Solutions','HL04SK Indicator',''),
('TKB000321','Spare Parts','Hotline Spire Kitchen Solutions','HL05SK Heater 2 KW - Heating element',''),
('TKB000322','Spare Parts','Hotline Spire Kitchen Solutions','HL06SK Temperature Display',''),
('TKB000323','Spare Parts','Induction Cooktop Butler','IC01TF Display controller',''),
('TKB000324','Spare Parts','Induction Cooktop Butler','IC02TF Main PCB',''),
('TKB000325','Spare Parts','Induction Cooktop Butler','IC03TF Ceramic Plate',''),
('TKB000326','Spare Parts','Induction Cooktop Butler','IC04TF Connecting Cable',''),
('TKB000327','Spare Parts','Juice Dispenser Elan Pro','JD1601ELP Tank Cover',''),
('TKB000328','Spare Parts','Juice Dispenser Elan Pro','JD1602ELP Tank',''),
('TKB000329','Spare Parts','Juice Dispenser Elan Pro','JD1603ELP Handle',''),
('TKB000330','Spare Parts','Juice Dispenser Elan Pro','JD1604ELP Gasket for tank',''),
('TKB000331','Spare Parts','Juice Dispenser Elan Pro','JD1605ELP Drain Tray',''),
('TKB000332','Spare Parts','Juice Dispenser Elan Pro','JD801ELP O-Ring',''),
('TKB000333','Spare Parts','Juice Dispenser Elan Pro','JD802ELP Pump tube',''),
('TKB000334','Spare Parts','Juice Dispenser Elan Pro','JD803ELP fastener',''),
('TKB000335','Spare Parts','Juice Dispenser Elan Pro','JD804ELP Tank Cover',''),
('TKB000336','Spare Parts','Juice Dispenser Elan Pro','JD805ELP Pump cover',''),
('TKB000337','Spare Parts','Juice Dispenser Elan Pro','JD806ELP Toggle switch',''),
('TKB000338','Spare Parts','Juice Dispenser Elan Pro','JD807ELP Tank',''),
('TKB000339','Spare Parts','Juice Dispenser Elan Pro','JD808ELP Handle',''),
('TKB000340','Spare Parts','Juice Dispenser Elan Pro','JD809ELP Gasket for tank',''),
('TKB000341','Spare Parts','Juice Dispenser Elan Pro','JD810ELP Drain Tray',''),
('TKB000342','Spare Parts','Lights Lighting Technolgies','L01SG LT Floret 20 W Tracklight WW - 3000 K CT',''),
('TKB000343','Spare Parts','Lights Lighting Technolgies','L02SG Track Channel 1Mtr - Track Channel 1Mtr',''),
('TKB000344','Spare Parts','Lights Lighting Technolgies','L03SG Suspension Kit',''),
('TKB000345','Spare Parts','Lights Lighting Technolgies','L04SG LT Wand 38 W - Aluminium Batten 4000 K',''),
('TKB000346','Spare Parts','Lights Lighting Technolgies','L05SG LED strip light - 5 Mter',''),
('TKB000347','Spare Parts','Lights Lighting Technolgies','L06SG 20Watt E27 bulb',''),
('TKB000348','Spare Parts','Merrychef','MC01ACE E2 Solid basket',''),
('TKB000349','Spare Parts','Merrychef','MC02ACE Paddle with hand guard and sides',''),
('TKB000350','Spare Parts','Merrychef','MC03ACE Flat cook plate',''),
('TKB000351','Spare Parts','Music System Jbl','MS01JBL Speaker',''),
('TKB000352','Spare Parts','Music System Jbl','MS02JBL Music system',''),
('TKB000353','Spare Parts','Music System Sony','MS01SNY Remote',''),
('TKB000354','Spare Parts','Music System Sony','MS02SNY speaker',''),
('TKB000355','Spare Parts','Music System Sony','MS03SNY Woofer',''),
('TKB000356','Spare Parts','Pest O Flash','PSF01PTS 15 Watt Tube - Blue',''),
('TKB000357','Spare Parts','Pest O Flash','PSF02PTS Transformer',''),
('TKB000358','Spare Parts','Pest O Flash','PSF03PTS Choke',''),
('TKB000359','Spare Parts','Pest O Flash','PSF04PTS Starter',''),
('TKB000360','Spare Parts','Plugpoint Legrand','PP01L Industrial shocket',''),
('TKB000361','Spare Parts','Plugpoint Legrand','PP02L Industrial plug',''),
('TKB000362','Spare Parts','Plugpoint Legrand','PP03L Industrial plug top Set',''),
('TKB000363','Spare Parts','Plugpoint Panasonic','PP01PS 6 Model Box',''),
('TKB000364','Spare Parts','Plugpoint Panasonic','PP02PS 16 A Switch',''),
('TKB000365','Spare Parts','Plugpoint Panasonic','PP03PS 6 A Switch',''),
('TKB000366','Spare Parts','Plugpoint Panasonic','PP04PS 6 Socket',''),
('TKB000367','Spare Parts','Plugpoint Panasonic','PP05PS 16 Socket',''),
('TKB000368','Spare Parts','Plugpoint Panasonic','PP06PS 6 Model plate',''),
('TKB000369','Spare Parts','Plugpoint Panasonic','PP07PS 3 Modell Plate',''),
('TKB000370','Spare Parts','Plugpoint Panasonic','PP08PS Black - 16 A Switch',''),
('TKB000371','Spare Parts','Plugpoint Panasonic','PP09PS Black - 6 A Switch',''),
('TKB000372','Spare Parts','Plugpoint Panasonic','PP10PS Black - 6 A Socket',''),
('TKB000373','Spare Parts','Plugpoint Panasonic','PP11PS Black - 16 A Socket',''),
('TKB000374','Spare Parts','Plugpoint Panasonic','PP12PS Black 6 Model plate',''),
('TKB000375','Spare Parts','Plugpoint Roma','PP01RM 16A Switch',''),
('TKB000376','Spare Parts','Plugpoint Roma','PP02RM 16A Socket',''),
('TKB000377','Spare Parts','Plugpoint Roma','PP03RM 6A Switch',''),
('TKB000378','Spare Parts','Plugpoint Roma','PP04RM 6A Socket',''),
('TKB000379','Spare Parts','Plugpoint Roma','PP05RM 6 Model Plate',''),
('TKB000380','Spare Parts','Plugpoint Roma','PP06RM 6 Model Box',''),
('TKB000381','Spare Parts','Plugpoint Roma','PP07RM 3 Model Box',''),
('TKB000382','Spare Parts','Plumbing Jaquar','PLB01JG washbasin',''),
('TKB000383','Spare Parts','Plumbing Jaquar','PLB02JG Wall Sink Mixture',''),
('TKB000384','Spare Parts','Plumbing Jaquar','PLB03JG Angle Cock',''),
('TKB000385','Spare Parts','Plumbing Jaquar','PLB04JG Tap Head ( Handle head )',''),
('TKB000386','Spare Parts','Plumbing Jaquar','PLB05JG Sink Jaalui - 4 Inch ( Viking round )',''),
('TKB000387','Spare Parts','Plumbing Jaquar','PLB06JG washbasin',''),
('TKB000388','Spare Parts','Plumbing Jaquar','PLB07JG RO tap ( Sink Cock )',''),
('TKB000389','Spare Parts','Plumbing Jaquar','PLB08JG WC seat cover',''),
('TKB000390','Spare Parts','Plumbing Jaquar','PLB09JG WC',''),
('TKB000391','Spare Parts','Plumbing Jaquar','PLB10JG Urinal',''),
('TKB000392','Spare Parts','Plumbing Jaquar','PLB11JG Spendle',''),
('TKB000393','Spare Parts','Pressure Cooker Hawkins','PC01HK Handle',''),
('TKB000394','Spare Parts','Pressure Cooker Hawkins','PC02HK Safety valve',''),
('TKB000395','Spare Parts','Pressure Cooker Hawkins','PC03HK Whistle',''),
('TKB000396','Spare Parts','Pressure Cooker Hawkins','PC04HK Rubber gasket',''),
('TKB000397','Spare Parts','Rice Cooker Panasonic','RC01PS Cast Heater',''),
('TKB000398','Spare Parts','Rice Cooker Panasonic','RC02PS Lever Assembly',''),
('TKB000399','Spare Parts','Rice Cooker Panasonic','RC03PS Centre Thermostat',''),
('TKB000400','Spare Parts','Rice Cooker Panasonic','RC04PS Thermal fuse assembly','');

INSERT INTO ticket_bucket (uid, department, category, sub_category_1, sub_category_2) VALUES
('TKB000401','Spare Parts','Rice Cooker Panasonic','RC05PS Cooking pan',''),
('TKB000402','Spare Parts','Rice Cooker Panasonic','RC06PS Lid assembly',''),
('TKB000403','Spare Parts','Rice Cooker Panasonic','RC07PS Mica heater',''),
('TKB000404','Spare Parts','Rice Cooker Panasonic','RC08PS Complete body',''),
('TKB000405','Spare Parts','Rice Cooker Panasonic','RC09PS power code',''),
('TKB000406','Spare Parts','Rice Cooker Panasonic','RC10PS Side handle',''),
('TKB000407','Spare Parts','Rice Cooker Panasonic','RC11PS Lid handle',''),
('TKB000408','Spare Parts','Rice Cooker Panasonic','RC12PS Bottom Plate',''),
('TKB000409','Spare Parts','Signage','SI01USF 100 watt',''),
('TKB000410','Spare Parts','SS Racks Artikel Inox','SSR01AI Bushes',''),
('TKB000411','Spare Parts','SS Racks Spire Kitchen Solutions','SSR01SK Metal Bushes',''),
('TKB000412','Spare Parts','Tortilla Press Star','TP01CF Thermostat',''),
('TKB000413','Spare Parts','Tortilla Press Star','TP02CF Hot plate - Top',''),
('TKB000414','Spare Parts','Tortilla Press Star','TP03CF Spring - Right',''),
('TKB000415','Spare Parts','Tortilla Press Star','TP04CF Knob',''),
('TKB000416','Spare Parts','Tortilla Press Star','TP05CF Spring - Left',''),
('TKB000417','Spare Parts','Tortilla Press Star','TP06CF Heater - TOP',''),
('TKB000418','Spare Parts','Tortilla Press Star','TP07CF Heater - Bottom',''),
('TKB000419','Spare Parts','Tortilla Press Waring','TP01WR Thermostat',''),
('TKB000420','Spare Parts','Tortilla Press Waring','TP02WR Leg Bushes',''),
('TKB000421','Spare Parts','Tortilla Press Waring','TP03WR High limit swith',''),
('TKB000422','Spare Parts','Trolley Spire Kitchen Solutions','TR01SK Trolley Wheel - Set of 4',''),
('TKB000423','Spare Parts','Under Counter Chiller Trufrost','UCC01TF Gasket',''),
('TKB000424','Spare Parts','Under Counter Chiller Trufrost','UCC02TF FAN MOTOR - Evoporator',''),
('TKB000425','Spare Parts','Under Counter Chiller Trufrost','UCC03TF CONTROLLER - Dixel',''),
('TKB000426','Spare Parts','Under Counter Chiller Trufrost','UCC04TF Hinges - Door',''),
('TKB000427','Spare Parts','Under Counter Chiller Trufrost','UCC05TF Fan motor - Condensor',''),
('TKB000428','Spare Parts','Under Counter Freezer Celfrost','UCF01CF Dixel & Subzero controller',''),
('TKB000429','Spare Parts','Under Counter Freezer Celfrost','UCF02CF Door hinges',''),
('TKB000430','Spare Parts','Under Counter Freezer Celfrost','UCF03CF Cooling fan motor',''),
('TKB000431','Spare Parts','Under Counter Freezer Celfrost','UCF04CF Condensor fan motor',''),
('TKB000432','Spare Parts','Under Counter Freezer Celfrost','UCF05CF Heater',''),
('TKB000433','Spare Parts','Under Counter Freezer Celfrost','UCF06CF Relay',''),
('TKB000434','Spare Parts','Under Counter Freezer Celfrost','UCF07CF Blower Motor',''),
('TKB000435','Spare Parts','Under Counter Freezer Celfrost','UCF08CF Blower blade',''),
('TKB000436','Spare Parts','Under Counter Freezer Celfrost','UCF09CF Gasket',''),
('TKB000437','Spare Parts','Under Counter Freezer Celfrost','UCF10CF Q Motor',''),
('TKB000438','Spare Parts','Under Counter Freezer Celfrost','UCF11CF Excel Fan Motor 4x4"',''),
('TKB000439','Spare Parts','Under Counter Freezer Trufrost','UCF01TF Dixel & Subzero controller',''),
('TKB000440','Spare Parts','Under Counter Freezer Trufrost','UCF02TF Door hing',''),
('TKB000441','Spare Parts','Under Counter Freezer Trufrost','UCF03TF Cooling fan motor',''),
('TKB000442','Spare Parts','Under Counter Freezer Trufrost','UCF04TF Condensor fan motor',''),
('TKB000443','Spare Parts','Under Counter Freezer Trufrost','UCF05TF Heater',''),
('TKB000444','Spare Parts','Under Counter Freezer Trufrost','UCF06TF Relay',''),
('TKB000445','Spare Parts','Under Counter Freezer Trufrost','UCF07TF Blower Motor',''),
('TKB000446','Spare Parts','Under Counter Freezer Trufrost','UCF08TF Blower blade',''),
('TKB000447','Spare Parts','Under Counter Freezer Trufrost','UCF09TF Gasket',''),
('TKB000448','Spare Parts','Under Counter Freezer Trufrost','UCF101TF Gasket',''),
('TKB000449','Spare Parts','Under Counter Freezer Trufrost','UCF102TF FAN MOTOR - Evoporator',''),
('TKB000450','Spare Parts','Under Counter Freezer Trufrost','UCF103TF CONTROLLER - Dixel',''),
('TKB000451','Spare Parts','Under Counter Freezer Trufrost','UCF104TF Hinges - Door',''),
('TKB000452','Spare Parts','Under Counter Freezer Trufrost','UCF105TF Fan motor - Condensor',''),
('TKB000453','Spare Parts','Visi Cooler Celfrost','VC01CFLL Front door hinges left lower',''),
('TKB000454','Spare Parts','Visi Cooler Celfrost','VC01CFLU Front door hinges left upper',''),
('TKB000455','Spare Parts','Visi Cooler Celfrost','VC01CFRL Front door hinges right lower',''),
('TKB000456','Spare Parts','Visi Cooler Celfrost','VC01CFRU Front door hinges right upper',''),
('TKB000457','Spare Parts','Visi Cooler Celfrost','VC02CF Door frame',''),
('TKB000458','Spare Parts','Visi Cooler Celfrost','VC03CF Gasket',''),
('TKB000459','Spare Parts','Visi Cooler Celfrost','VC04CF Door Hinges',''),
('TKB000460','Spare Parts','Visi Cooler Celfrost','VC05CF Strip LED light',''),
('TKB000461','Spare Parts','Visi Cooler Celfrost','VC06CF Condensor',''),
('TKB000462','Spare Parts','Visi Cooler Celfrost','VC07CF Condensor fan',''),
('TKB000463','Spare Parts','Visi Cooler Celfrost','VC08CF Cooling can',''),
('TKB000464','Spare Parts','Visi Cooler Celfrost','VC09CF Cooling coil',''),
('TKB000465','Spare Parts','Visi Cooler Celfrost','VC10CF Door closer',''),
('TKB000466','Spare Parts','Weighing Scale - 150 Kg Essae','WSB01AWS Power Chord',''),
('TKB000467','Spare Parts','Weighing Scale - 150 Kg Essae','WSB02AWS Battery 6 V',''),
('TKB000468','Spare Parts','Weighing Scale - 150 Kg Essae','WSB03AWS Load Shell - 150 Kg',''),
('TKB000469','Spare Parts','Weighing Scale - 6 Kg Essae','WSS01AWS Load Shell - 6 Kg',''),
('TKB000470','Spare Parts','Weighing Scale - 6 Kg Essae','WSS02AWS Battery 6 V',''),
('TKB000471','Spare Parts','Weighing Scale - 6 Kg Essae','WSS03AWS Battery Cover',''),
('TKB000472','Maintenance','AC','Cleaning',''),
('TKB000473','Maintenance','AC','Cooling',''),
('TKB000474','Maintenance','AC','Display',''),
('TKB000475','Maintenance','AC','Not Getting On',''),
('TKB000476','Maintenance','AC','Remote',''),
('TKB000477','Maintenance','AC','Water Leakage',''),
('TKB000478','Maintenance','AirCurtain','Noisy',''),
('TKB000479','Maintenance','AirCurtain','Not getting on',''),
('TKB000480','Maintenance','AirCurtain','Sensor issue',''),
('TKB000481','Maintenance','Biometric','Not getting on',''),
('TKB000482','Maintenance','Booth/Bench','Laminate Peeling',''),
('TKB000483','Maintenance','Booth/Bench','Open Gap',''),
('TKB000484','Maintenance','Booth/Bench','Polishing',''),
('TKB000485','Maintenance','Booth/Bench','Upholstery',''),
('TKB000486','Maintenance','Chair','Broken',''),
('TKB000487','Maintenance','Chair','Loose Joints',''),
('TKB000488','Maintenance','Chair','Other',''),
('TKB000489','Maintenance','Chair','Upholstery',''),
('TKB000490','Maintenance','Chair','Wobbling',''),
('TKB000491','Maintenance','ChestFreezer','Door Broken',''),
('TKB000492','Maintenance','ChestFreezer','Gasket Broken',''),
('TKB000493','Maintenance','ChestFreezer','Ice Formation',''),
('TKB000494','Maintenance','ChestFreezer','Not Cooling at all',''),
('TKB000495','Maintenance','ChestFreezer','Not getting on',''),
('TKB000496','Maintenance','ChestFreezer','Required temp not met',''),
('TKB000497','Maintenance','ChestFreezer','SS cladding',''),
('TKB000498','Maintenance','ChestFreezer','Water Leakage',''),
('TKB000499','Maintenance','Civil','Broken Tiles',''),
('TKB000500','Maintenance','Civil','Drain Chamber issue',''),
('TKB000501','Maintenance','Civil','Gap Closure',''),
('TKB000502','Maintenance','Civil','Masonary',''),
('TKB000503','Maintenance','Civil','Painting',''),
('TKB000504','Maintenance','Civil','Polishing',''),
('TKB000505','Maintenance','Civil','SS cladding',''),
('TKB000506','Maintenance','Civil','Tiling',''),
('TKB000507','Maintenance','Civil','Wall Hanging',''),
('TKB000508','Maintenance','ColdBainMarie-ColdLine','Display Issue',''),
('TKB000509','Maintenance','ColdBainMarie-ColdLine','Door Broken',''),
('TKB000510','Maintenance','ColdBainMarie-ColdLine','Door Issue',''),
('TKB000511','Maintenance','ColdBainMarie-ColdLine','Gasket',''),
('TKB000512','Maintenance','ColdBainMarie-ColdLine','Ice Formation',''),
('TKB000513','Maintenance','ColdBainMarie-ColdLine','Not Cooling at all',''),
('TKB000514','Maintenance','ColdBainMarie-ColdLine','Not getting on',''),
('TKB000515','Maintenance','ColdBainMarie-ColdLine','Required temp not met',''),
('TKB000516','Maintenance','ColdRoom','Display Issue',''),
('TKB000517','Maintenance','ColdRoom','Door Issue',''),
('TKB000518','Maintenance','ColdRoom','Gasket Broken',''),
('TKB000519','Maintenance','ColdRoom','Ice Formation',''),
('TKB000520','Maintenance','ColdRoom','Not Cooling at all',''),
('TKB000521','Maintenance','ColdRoom','Required temp not met',''),
('TKB000522','Maintenance','ColdRoom','Strip curtains',''),
('TKB000523','Maintenance','ColdRoom','Water Leakage',''),
('TKB000524','Maintenance','DG','Display Issue',''),
('TKB000525','Maintenance','DG','Not getting on',''),
('TKB000526','Maintenance','DG','Running Continuously',''),
('TKB000527','Maintenance','DG','Turning Off',''),
('TKB000528','Maintenance','Drawer/WoodenCabinet','Channel Issue',''),
('TKB000529','Maintenance','Drawer/WoodenCabinet','Handle',''),
('TKB000530','Maintenance','Drawer/WoodenCabinet','Hinges issue',''),
('TKB000531','Maintenance','Drawer/WoodenCabinet','Laminate Peeling',''),
('TKB000532','Maintenance','Drawer/WoodenCabinet','Lock issue',''),
('TKB000533','Maintenance','Drawer/WoodenCabinet','Shelf',''),
('TKB000534','Maintenance','Electrical/DBBoard','Equipment Shock',''),
('TKB000535','Maintenance','Electrical/DBBoard','Labelling',''),
('TKB000536','Maintenance','Electrical/DBBoard','MCB Tripping',''),
('TKB000537','Maintenance','Electrical/DBBoard','Wire Covering',''),
('TKB000538','Maintenance','ElectricFryer','Buzzer is not working',''),
('TKB000539','Maintenance','ElectricFryer','Fire Coming Out',''),
('TKB000540','Maintenance','ElectricFryer','Not getting on',''),
('TKB000541','Maintenance','ElectricFryer','Oil Leakage',''),
('TKB000542','Maintenance','ElectricFryer','Temp Issue',''),
('TKB000543','Maintenance','Exhaust/FreshAir/Airwasher','Air Balancing',''),
('TKB000544','Maintenance','Exhaust/FreshAir/Airwasher','Cooling',''),
('TKB000545','Maintenance','Exhaust/FreshAir/Airwasher','Noisy',''),
('TKB000546','Maintenance','Exhaust/FreshAir/Airwasher','Not getting on',''),
('TKB000547','Maintenance','Exhaust/FreshAir/Airwasher','Oil Dripping',''),
('TKB000548','Maintenance','Exhaust/FreshAir/Airwasher','Water Leakage',''),
('TKB000549','Maintenance','Exhaust/FreshAir/Airwasher','Weak Airflow',''),
('TKB000550','Maintenance','ExhaustHood/SS Equipments/SS Tables/ SS Racks /SneezeGuard','Bushes',''),
('TKB000551','Maintenance','ExhaustHood/SS Equipments/SS Tables/ SS Racks /SneezeGuard','Exhuast hood - Filter Fixing',''),
('TKB000552','Maintenance','ExhaustHood/SS Equipments/SS Tables/ SS Racks /SneezeGuard','Fixing',''),
('TKB000553','Maintenance','ExhaustHood/SS Equipments/SS Tables/ SS Racks /SneezeGuard','Requirement',''),
('TKB000554','Maintenance','FAS/GLDSystem','Leakage is not getting Detected',''),
('TKB000555','Maintenance','FAS/GLDSystem','Not working',''),
('TKB000556','Maintenance','FireExtinguisher/FireSafety','Empty',''),
('TKB000557','Maintenance','FireExtinguisher/FireSafety','Expired',''),
('TKB000558','Maintenance','FireExtinguisher/FireSafety','Fire Blanket',''),
('TKB000559','Maintenance','FireExtinguisher/FireSafety','Hood Supression Expired',''),
('TKB000560','Maintenance','FireExtinguisher/FireSafety','Stand Required',''),
('TKB000561','Maintenance','FireExtinguisher/FireSafety','Tag Missing',''),
('TKB000562','Maintenance','FireExtinguisher/FireSafety','Wall Hanging',''),
('TKB000563','Maintenance','GasBurner','Balancing',''),
('TKB000564','Maintenance','GasBurner','Burner Grid damaged',''),
('TKB000565','Maintenance','GasBurner','Burner Leakage',''),
('TKB000566','Maintenance','GasBurner','Flame Issues',''),
('TKB000567','Maintenance','GasBurner','Gas Pipe Leakage',''),
('TKB000568','Maintenance','GasBurner','Needs Service',''),
('TKB000569','Maintenance','GasFryer','Fire Coming Out',''),
('TKB000570','Maintenance','GasFryer','Gas Pipe Leakage',''),
('TKB000571','Maintenance','GasFryer','Not getting on',''),
('TKB000572','Maintenance','GasFryer','Oil Leakage',''),
('TKB000573','Maintenance','GasFryer','Temp Issue',''),
('TKB000574','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Gas Line Leakage',''),
('TKB000575','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Gas Line Painting',''),
('TKB000576','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Gas not getting in Store',''),
('TKB000577','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Gas pressure issue',''),
('TKB000578','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Gas Regulator Issue',''),
('TKB000579','Maintenance','GasLeakage/Pressuure/ Gas line /Bank','Meter Guage Issue',''),
('TKB000580','Maintenance','Geyser','Geyser Leakage',''),
('TKB000581','Maintenance','Geyser','Not getting on',''),
('TKB000582','Maintenance','Geyser','Pipe Leakage',''),
('TKB000583','Maintenance','Geyser','Temp Issue',''),
('TKB000584','Maintenance','GlassDoor/Doors','Glass door Gap',''),
('TKB000585','Maintenance','GlassDoor/Door','Glass Door Handle',''),
('TKB000586','Maintenance','GlassDoor/Door','Glass Door Lock',''),
('TKB000587','Maintenance','GlassDoor/Door','Door not closing',''),
('TKB000588','Maintenance','GlassDoor/Door','Door Chipping',''),
('TKB000589','Maintenance','GlassDoor/Door','Door Handle',''),
('TKB000590','Maintenance','GlassDoor/Door','Door Lock',''),
('TKB000591','Maintenance','GreaseTrap','Broken',''),
('TKB000592','Maintenance','GreaseTrap','Leaking',''),
('TKB000593','Maintenance','GreaseTrap','Missing Filter',''),
('TKB000594','Maintenance','GreaseTrap','Missing Lid',''),
('TKB000595','Maintenance','GreaseTrap','Not working',''),
('TKB000596','Maintenance','GreaseTrap','Valve Issue',''),
('TKB000597','Maintenance','Grinder/Mixer','Not Getting Grinding',''),
('TKB000598','Maintenance','Grinder/Mixer','Not working',''),
('TKB000599','Maintenance','HotBainMarie-Hotline','Divider issue',''),
('TKB000600','Maintenance','HotBainMarie-Hotline','Leaking','');

INSERT INTO ticket_bucket (uid, department, category, sub_category_1, sub_category_2) VALUES
('TKB000601','Maintenance','HotBainMarie-Hotline','Leg Bushes',''),
('TKB000602','Maintenance','HotBainMarie-Hotline','Not getting on',''),
('TKB000603','Maintenance','HotBainMarie-Hotline','On  - Heater not working',''),
('TKB000604','Maintenance','HotBainMarie-Hotline','Shock',''),
('TKB000605','Maintenance','HotBainMarie-Hotline','Temp Issue',''),
('TKB000606','Maintenance','HotCabinet','Castor Wheel',''),
('TKB000607','Maintenance','HotCabinet','Door Not Closing',''),
('TKB000608','Maintenance','HotCabinet','Gaskets',''),
('TKB000609','Maintenance','HotCabinet','Not getting on',''),
('TKB000610','Maintenance','HotCabinet','Shock',''),
('TKB000611','Maintenance','HotCabinet','Temp Issue',''),
('TKB000612','Maintenance','InductionCookTop','Glass Broken',''),
('TKB000613','Maintenance','InductionCookTop','Heating Issue',''),
('TKB000614','Maintenance','InductionCookTop','Not getting on',''),
('TKB000615','Maintenance','InductionCookTop','Shock',''),
('TKB000616','Maintenance','InductionCookTop','Switch/Buttons',''),
('TKB000617','Maintenance','JuiceDispenser','Broken Jar/Lid',''),
('TKB000618','Maintenance','JuiceDispenser','Broken Nozzle/Tap',''),
('TKB000619','Maintenance','JuiceDispenser','Leaking',''),
('TKB000620','Maintenance','JuiceDispenser','Not Cooling',''),
('TKB000621','Maintenance','JuiceDispenser','Not Fixing properly',''),
('TKB000622','Maintenance','JuiceDispenser','Not getting on',''),
('TKB000623','Maintenance','Lights','fascade Downlights',''),
('TKB000624','Maintenance','Lights','Grazer lights',''),
('TKB000625','Maintenance','Lights','Hanging Light',''),
('TKB000626','Maintenance','Lights','LED Bulbs',''),
('TKB000627','Maintenance','Lights','LED Strip',''),
('TKB000628','Maintenance','Lights','Need to fix properly',''),
('TKB000629','Maintenance','Lights','Serving Line Light',''),
('TKB000630','Maintenance','Lights','Track Light',''),
('TKB000631','Maintenance','Lights','Tube Light',''),
('TKB000632','Maintenance','MarketingBoards/Standees/OrderHereBoard/Tito','Welding',''),
('TKB000633','Maintenance','MerryChef','Display Issue',''),
('TKB000634','Maintenance','MerryChef','Filter issue',''),
('TKB000635','Maintenance','MerryChef','Noisy',''),
('TKB000636','Maintenance','MerryChef','Not getting on',''),
('TKB000637','Maintenance','MerryChef','Temp Issue',''),
('TKB000638','Maintenance','Mirror','Broken',''),
('TKB000639','Maintenance','MultiKitchenTimers','Not Functioning',''),
('TKB000640','Maintenance','MultiKitchenTimers','Not getting on',''),
('TKB000641','Maintenance','MusicSystem/Speaker','Amplifier Not Working',''),
('TKB000642','Maintenance','MusicSystem/Speaker','Muffled Sound',''),
('TKB000643','Maintenance','MusicSystem/Speaker','Not getting on',''),
('TKB000644','Maintenance','MusicSystem/Speaker','Remote issue',''),
('TKB000645','Maintenance','MusicSystem/Speaker','Speaker Not Working',''),
('TKB000646','Maintenance','MusicSystem/Speaker','Uneven Sound',''),
('TKB000647','Maintenance','Others','Others',''),
('TKB000648','Maintenance','PestoFlash','Light Not Working',''),
('TKB000649','Maintenance','PestoFlash','Not working',''),
('TKB000650','Maintenance','PestoFlash','Need Gum Pad',''),
('TKB000651','Maintenance','PestoFlash','Need to Shift',''),
('TKB000652','Maintenance','PestoFlash','Not getting on',''),
('TKB000653','Maintenance','PlugPoint/MCB','Customer Plug Point',''),
('TKB000654','Maintenance','PlugPoint/MCB','Industrial Sockets Issue',''),
('TKB000655','Maintenance','PlugPoint/MCB','Kitchen Plug Point',''),
('TKB000656','Maintenance','PlugPoint/MCB','MCB is tripping',''),
('TKB000657','Maintenance','PlugPoint/MCB','Need Extra Connection Points',''),
('TKB000658','Maintenance','PlugPoint/MCB','Switch board Issue',''),
('TKB000659','Maintenance','PlugPoint/MCB','Wlan Port issue',''),
('TKB000660','Maintenance','Plumbing','3 Sink Pipe Leakage',''),
('TKB000661','Maintenance','Plumbing','3 Sink Pipe line Block',''),
('TKB000662','Maintenance','Plumbing','Main Drain Choked',''),
('TKB000663','Maintenance','Plumbing','Raw Water is not coming',''),
('TKB000664','Maintenance','Plumbing','Raw Water is slow',''),
('TKB000665','Maintenance','Plumbing','Seepage issue',''),
('TKB000666','Maintenance','Plumbing','Wash Basin Issue',''),
('TKB000667','Maintenance','PressureCooker','Gasket issue',''),
('TKB000668','Maintenance','PressureCooker','Handle Issue',''),
('TKB000669','Maintenance','PressureCooker','Leakage',''),
('TKB000670','Maintenance','PressureCooker','Not Cooking Properly',''),
('TKB000671','Maintenance','PressureCooker','Safety valve need to fix',''),
('TKB000672','Maintenance','PressureCooker','Whistle Top',''),
('TKB000673','Maintenance','RiceCooker','Auto-Warm Not Working',''),
('TKB000674','Maintenance','RiceCooker','Broken Lid/Handle',''),
('TKB000675','Maintenance','RiceCooker','Gas Pipe Leakage',''),
('TKB000676','Maintenance','RiceCooker','Not getting on',''),
('TKB000677','Maintenance','RiceCooker','Over heating',''),
('TKB000678','Maintenance','RiceCooker','Rice Not cooking Properly',''),
('TKB000679','Maintenance','RiceCooker','Shock',''),
('TKB000680','Maintenance','RobotCoupe','Blade - 15mm Dice',''),
('TKB000681','Maintenance','RobotCoupe','Blade - 15mm Slice',''),
('TKB000682','Maintenance','RobotCoupe','Blade - 5MM Dice',''),
('TKB000683','Maintenance','RobotCoupe','Blade - 5mm Slice',''),
('TKB000684','Maintenance','RobotCoupe','Blade - Grater',''),
('TKB000685','Maintenance','RobotCoupe','Hanger Issue',''),
('TKB000686','Maintenance','RobotCoupe','Not getting on',''),
('TKB000687','Maintenance','RO-WaterPurifier','Leakage issue',''),
('TKB000688','Maintenance','RO-WaterPurifier','No Auto-Cut',''),
('TKB000689','Maintenance','RO-WaterPurifier','Not getting on',''),
('TKB000690','Maintenance','RO-WaterPurifier','Slow Flow',''),
('TKB000691','Maintenance','RO-WaterPurifier','Tank Needs Cleaning',''),
('TKB000692','Maintenance','RO-WaterPurifier','Tap Issue',''),
('TKB000693','Maintenance','RO-WaterPurifier','Taste is Bad',''),
('TKB000694','Maintenance','Safe Locker','Forgot Password',''),
('TKB000695','Maintenance','Safe Locker','Loose/Movable',''),
('TKB000696','Maintenance','Safe Locker','Not Closing',''),
('TKB000697','Maintenance','Safe Locker','Not getting on',''),
('TKB000698','Maintenance','Safe Locker','Not Opening',''),
('TKB000699','Maintenance','Safe Locker','Password Change',''),
('TKB000700','Maintenance','Sealing Machine','Heating Issue',''),
('TKB000701','Maintenance','Sealing Machine','Not getting on',''),
('TKB000702','Maintenance','Sealing Machine','Sheet Replace',''),
('TKB000703','Maintenance','Sealing Machine','Sheet Replacement',''),
('TKB000704','Maintenance','Signage','Damaged',''),
('TKB000705','Maintenance','Signage','Letter Alignment',''),
('TKB000706','Maintenance','Signage','Letter Fell Down',''),
('TKB000707','Maintenance','Signage','Needs Cleaning',''),
('TKB000708','Maintenance','Signage','Not getting on',''),
('TKB000709','Maintenance','Signage','Requirement',''),
('TKB000710','Maintenance','Double/Four  Door Chiller','Castor Wheel',''),
('TKB000711','Maintenance','Double/Four  Door Chiller','Display Issue',''),
('TKB000712','Maintenance','Double/Four  Door Chiller','Door Broken',''),
('TKB000713','Maintenance','Double/Four  Door Chiller','Gasket Broken',''),
('TKB000714','Maintenance','Double/Four  Door Chiller','Ice Formation',''),
('TKB000715','Maintenance','Double/Four  Door Chiller','Not Cooling at all',''),
('TKB000716','Maintenance','Double/Four  Door Chiller','Required temp not met',''),
('TKB000717','Maintenance','Double/Four  Door Chiller','Water Leakage',''),
('TKB000718','Maintenance','Double/Four  Door Chiller','Wired Shelve',''),
('TKB000719','Maintenance','Double/Four door Freezer','Display Issue',''),
('TKB000720','Maintenance','Double/Four door Freezer','Door Broken',''),
('TKB000721','Maintenance','Double/Four door Freezer','Gasket Broken',''),
('TKB000722','Maintenance','Double/Four door Freezer','Ice Formation',''),
('TKB000723','Maintenance','Double/Four door Freezer','Not Cooling at all',''),
('TKB000724','Maintenance','Double/Four door Freezer','Not getting on',''),
('TKB000725','Maintenance','Double/Four door Freezer','Required temp not met',''),
('TKB000726','Maintenance','Double/Four door Freezer','Water Leakage',''),
('TKB000727','Maintenance','Double/Four door Freezer','Wired Shelve',''),
('TKB000728','Maintenance','StaffRoom','Fan Not working',''),
('TKB000729','Maintenance','StaffRoom','Fan Requirement',''),
('TKB000730','Maintenance','StaffRoom','Lights Issue',''),
('TKB000731','Maintenance','StaffRoom','Painting Requirement',''),
('TKB000732','Maintenance','StaffRoom','Pest Control',''),
('TKB000733','Maintenance','StaffRoom','Plumbing',''),
('TKB000734','Maintenance','StaffRoom','Power issue',''),
('TKB000735','Maintenance','StorageContainers','Caster Wheels Damage',''),
('TKB000736','Maintenance','StorageContainers','Damage',''),
('TKB000737','Maintenance','StorageContainers','Storage Container Glass Removed',''),
('TKB000738','Maintenance','Dine In Tables','Laminate/SS Sheet Peeling',''),
('TKB000739','Maintenance','Dine In Tables','Paint',''),
('TKB000740','Maintenance','Dine In Tables','Sharp',''),
('TKB000741','Maintenance','Dine In Tables','Wobbling',''),
('TKB000742','Maintenance','Tawa/GriddlePlate','Burner Leakage',''),
('TKB000743','Maintenance','Tawa/GriddlePlate','Gas Pipe Leakage',''),
('TKB000744','Maintenance','Tawa/GriddlePlate','Leakage issue',''),
('TKB000745','Maintenance','Tawa/GriddlePlate','Low Temperature',''),
('TKB000746','Maintenance','Tawa/GriddlePlate','Needs Service',''),
('TKB000747','Maintenance','Tawa/GriddlePlate','Not getting on',''),
('TKB000748','Maintenance','Tawa/GriddlePlate','Shock',''),
('TKB000749','Maintenance','Thermometer-Infrared','Not getting on',''),
('TKB000750','Maintenance','Thermometer-Infrared','Other',''),
('TKB000751','Maintenance','Thermometer-Infrared','Wrong Temp',''),
('TKB000752','Maintenance','Thermometer-Probe','Not getting on',''),
('TKB000753','Maintenance','Thermometer-Probe','Other',''),
('TKB000754','Maintenance','Thermometer-Probe','Wrong Temp',''),
('TKB000755','Maintenance','Toilet/Restroom','Western Commode block',''),
('TKB000756','Maintenance','Toilet/Restroom','Health Faucet gun not working/Leakage',''),
('TKB000757','Maintenance','Toilet/Restroom','Western Commode Seat Issue',''),
('TKB000758','Maintenance','Toilet/Restroom','Always Running Water',''),
('TKB000759','Maintenance','Toilet/Restroom','Blockage',''),
('TKB000760','Maintenance','Toilet/Restroom','No Water',''),
('TKB000761','Maintenance','Toilet/Restroom','Toilet Exhaust issue',''),
('TKB000762','Maintenance','Toilet/Restroom','Seepage issue',''),
('TKB000763','Maintenance','Toilet/Restroom','Water leakage issue',''),
('TKB000764','Maintenance','TortillaPress','Heating isssue',''),
('TKB000765','Maintenance','TortillaPress','Hinges issue',''),
('TKB000766','Maintenance','TortillaPress','Not getting on',''),
('TKB000767','Maintenance','TortillaPress','Shock',''),
('TKB000768','Maintenance','TortillaPress','Warped Plate',''),
('TKB000769','Maintenance','Trolley','Castor Wheel Broken',''),
('TKB000770','Maintenance','Trolley','Handle Broken',''),
('TKB000771','Maintenance','Trolley','Other',''),
('TKB000772','Maintenance','Trolley','Requirement',''),
('TKB000773','Maintenance','TVMenu','Alignment',''),
('TKB000774','Maintenance','TVMenu','Brightness Issue',''),
('TKB000775','Maintenance','TVMenu','Not getting on',''),
('TKB000776','Maintenance','TVMenu','Remote',''),
('TKB000777','Maintenance','TVMenu','Screen Damaged',''),
('TKB000778','Maintenance','UPS/Inverter','Not Giving the Backup',''),
('TKB000779','Maintenance','UPS/Inverter','Not working',''),
('TKB000780','Maintenance','Utilities','Energy Meter Not working',''),
('TKB000781','Maintenance','Utilities','Gas meter Not working',''),
('TKB000782','Maintenance','Utilities','Water meter Not working',''),
('TKB000783','Maintenance','VisiCooler/BackbarChiller','Door Issue',''),
('TKB000784','Maintenance','VisiCooler/BackbarChiller','Light issue',''),
('TKB000785','Maintenance','VisiCooler/BackbarChiller','Not getting on',''),
('TKB000786','Maintenance','VisiCooler/BackbarChiller','Temperature Issue',''),
('TKB000787','Maintenance','VisiCooler/BackbarChiller','Water Leakage',''),
('TKB000788','Maintenance','WaterTaps','3 Sink Taps Leakge/ Not working',''),
('TKB000789','Maintenance','WaterTaps','Bathroom Taps Not working /Leakage',''),
('TKB000790','Maintenance','WaterTaps','RO taps Not Working/Leakage',''),
('TKB000791','Maintenance','WaterTaps','Wash Basin Tap leakage',''),
('TKB000792','Maintenance','WaterTaps','Wash Basin Tap Loosen',''),
('TKB000793','Maintenance','WeightScale-Large','Display Issue',''),
('TKB000794','Maintenance','WeightScale-Large','Not Accurate',''),
('TKB000795','Maintenance','WeightScale-Large','Not Charging',''),
('TKB000796','Maintenance','WeightScale-Large','Not getting on',''),
('TKB000797','Maintenance','WeightScale-Large','Stamping',''),
('TKB000798','Maintenance','WeightScale-Small','Display Issue',''),
('TKB000799','Maintenance','WeightScale-Small','Not Accurate',''),
('TKB000800','Maintenance','WeightScale-Small','Not Charging','');

INSERT INTO ticket_bucket (uid, department, category, sub_category_1, sub_category_2) VALUES
('TKB000801','Maintenance','WeightScale-Small','Not getting on',''),
('TKB000802','Maintenance','WeightScale-Small','Stamping',''),
('TKB000803','Maintenance','Under counter Freezer','Display Issue',''),
('TKB000804','Maintenance','Under counter Freezer','Door Broken',''),
('TKB000805','Maintenance','Under counter Freezer','Gasket Broken',''),
('TKB000806','Maintenance','Under counter Freezer','Ice Formation',''),
('TKB000807','Maintenance','Under counter Freezer','Not Cooling at all',''),
('TKB000808','Maintenance','Under counter Freezer','Not getting on',''),
('TKB000809','Maintenance','Under counter Freezer','Required temp not met',''),
('TKB000810','Maintenance','Under counter Freezer','Water Leakage',''),
('TKB000811','Maintenance','Under counter Freezer','Wired Shelve',''),
('TKB000812','Maintenance','Under counter chiller','Display Issue',''),
('TKB000813','Maintenance','Under counter chiller','Door Broken',''),
('TKB000814','Maintenance','Under counter chiller','Gasket Broken',''),
('TKB000815','Maintenance','Under counter chiller','Ice Formation',''),
('TKB000816','Maintenance','Under counter chiller','Not Cooling at all',''),
('TKB000817','Maintenance','Under counter chiller','Not getting on',''),
('TKB000818','Maintenance','Under counter chiller','Required temp not met',''),
('TKB000819','Maintenance','Under counter chiller','Water Leakage',''),
('TKB000820','Maintenance','Under counter chiller','Wired Shelve',''),
('TKB000821','Maintenance','Water test Reports-Doing by third Party','Required',''),
('TKB000822','Maintenance','Food test Reports-Doing by Third party','Required',''),
('TKB000823','Maintenance','TB HotBainMarie-Hotline','Leaking',''),
('TKB000824','Maintenance','TB HotBainMarie-Hotline','Leg Bushes',''),
('TKB000825','Maintenance','TB HotBainMarie-Hotline','Not getting on',''),
('TKB000826','Maintenance','TB HotBainMarie-Hotline','On  - Heater not working',''),
('TKB000827','Maintenance','TB HotBainMarie-Hotline','Shock',''),
('TKB000828','Maintenance','TB HotBainMarie-Hotline','Temp Issue',''),
('TKB000829','Maintenance','Wall Fan','Not working',''),
('TKB000830','Maintenance','Wall Fan','Needs Service','');
