package com.ampairs.analytics.domain.model

import com.ampairs.analytics.domain.enums.Confidence
import com.ampairs.analytics.domain.enums.ForecastMethod
import com.ampairs.core.domain.model.OwnableBaseDomain
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Index
import jakarta.persistence.Table
import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate

/**
 * Per-product, per-period demand projection (R5). Generated by the nightly forecast batch and pulled
 * read-only to mobile via the canonical `GET /sync` feed. Never written by clients.
 */
@Entity(name = "demand_forecast")
@Table(
    name = "demand_forecast",
    indexes = [
        Index(name = "idx_forecast_uid", columnList = "uid", unique = true),
        Index(name = "ux_forecast_key", columnList = "owner_id, product_id, period_start, horizon", unique = true),
        Index(name = "ix_forecast_sync", columnList = "owner_id, updated_at"),
        Index(name = "ix_forecast_product", columnList = "owner_id, product_id, period_start"),
    ],
)
class DemandForecast : OwnableBaseDomain() {

    @Column(name = "product_id", nullable = false, length = 64)
    var productId: String = ""

    @Column(name = "period_start", nullable = false)
    var periodStart: LocalDate = LocalDate.EPOCH

    @Column(name = "horizon", nullable = false)
    var horizon: Int = 1

    @Column(name = "mean_qty", nullable = false, precision = 19, scale = 3)
    var meanQty: BigDecimal = BigDecimal.ZERO

    @Column(name = "std_dev_qty", nullable = false, precision = 19, scale = 3)
    var stdDevQty: BigDecimal = BigDecimal.ZERO

    @Enumerated(EnumType.STRING)
    @Column(name = "method", nullable = false, length = 16)
    var method: ForecastMethod = ForecastMethod.MOVING_AVG

    @Enumerated(EnumType.STRING)
    @Column(name = "confidence", nullable = false, length = 8)
    var confidence: Confidence = Confidence.LOW

    @Column(name = "generated_at", nullable = false)
    var generatedAt: Instant = Instant.now()

    override fun obtainSeqIdPrefix(): String = "DFC"
}
