package com.ampairs.order.domain.enums

enum class OrderStatus {
    DRAFT, NEW, ORDERED, CONFIRMED, PROCESSING, SHIPPED, OUT_FOR_DELIVERY, DELIVERED, CANCELLED,
    REFUNDED, PENDING_MERCHANT_REVIEW, INVOICED,
}