package com.ampairs.inventory

import com.ampairs.inventory.domain.model.InventoryConfig
import com.ampairs.inventory.repository.InventoryConfigRepository
import com.ampairs.inventory.service.InventoryConfigService
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertSame
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.Mock
import org.mockito.Mockito.verify
import org.mockito.junit.jupiter.MockitoExtension
import org.mockito.junit.jupiter.MockitoSettings
import org.mockito.kotlin.any
import org.mockito.kotlin.whenever
import org.mockito.quality.Strictness

@ExtendWith(MockitoExtension::class)
@MockitoSettings(strictness = Strictness.LENIENT)
class InventoryConfigServiceTest {

    @Mock
    private lateinit var repository: InventoryConfigRepository

    private lateinit var service: InventoryConfigService

    private fun config(block: InventoryConfig.() -> Unit = {}): InventoryConfig =
        InventoryConfig().apply {
            uid = "CFG-1"
            block()
        }

    @BeforeEach
    fun setUp() {
        service = InventoryConfigService(repository)
        whenever(repository.save(any<InventoryConfig>())).thenAnswer { it.arguments[0] }
    }

    @Test
    fun `getOrCreateConfig returns existing config`() {
        val existing = config()
        whenever(repository.findFirstByOrderByCreatedAtDesc()).thenReturn(existing)

        assertSame(existing, service.getOrCreateConfig())
        verify(repository, org.mockito.Mockito.never()).save(any<InventoryConfig>())
    }

    @Test
    fun `getOrCreateConfig creates default when none exists`() {
        whenever(repository.findFirstByOrderByCreatedAtDesc()).thenReturn(null)

        val result = service.getOrCreateConfig()

        // Default entity values
        assertEquals("FIFO", result.stockConsumptionStrategy)
        assertTrue(result.enableLowStockAlerts)
        assertFalse(result.allowNegativeStock)
        verify(repository).save(any<InventoryConfig>())
    }

    @Test
    fun `getConfigByUid delegates`() {
        val c = config()
        whenever(repository.findByUid("CFG-1")).thenReturn(c)
        assertSame(c, service.getConfigByUid("CFG-1"))
        whenever(repository.findByUid("none")).thenReturn(null)
        assertNull(service.getConfigByUid("none"))
    }

    @Test
    fun `updateConfig copies all fields`() {
        val existing = config()
        whenever(repository.findByUid("CFG-1")).thenReturn(existing)
        val updates = config {
            autoDeductOnOrder = true
            allowManualOverride = false
            blockOrdersWhenOutOfStock = true
            stockConsumptionStrategy = "FEFO"
            enableBatchTrackingByDefault = true
            enableSerialTrackingByDefault = true
            enableExpiryTrackingByDefault = true
            enableLowStockAlerts = false
            enableExpiryAlerts = false
            expiryAlertDays = 10
            enableOverstockAlerts = true
            allowNegativeStock = true
            requireApprovalForAdjustments = true
            defaultWarehouseId = "WHR-9"
            autoGenerateDailyLedger = false
            ledgerGenerationHour = 5
        }

        val result = service.updateConfig("CFG-1", updates)

        assertTrue(result.autoDeductOnOrder)
        assertFalse(result.allowManualOverride)
        assertEquals("FEFO", result.stockConsumptionStrategy)
        assertEquals(10, result.expiryAlertDays)
        assertTrue(result.allowNegativeStock)
        assertEquals("WHR-9", result.defaultWarehouseId)
        assertEquals(5, result.ledgerGenerationHour)
    }

    @Test
    fun `updateConfig not found throws`() {
        whenever(repository.findByUid("X")).thenReturn(null)
        assertThrows(IllegalArgumentException::class.java) {
            service.updateConfig("X", config())
        }
    }

    @Test
    fun `convenience getters read from config`() {
        val c = config {
            autoDeductOnOrder = true
            allowManualOverride = false
            allowNegativeStock = true
            stockConsumptionStrategy = "LIFO"
            defaultWarehouseId = "WHR-DEF"
        }
        whenever(repository.findFirstByOrderByCreatedAtDesc()).thenReturn(c)

        assertTrue(service.isAutoDeductEnabled())
        assertFalse(service.isManualOverrideAllowed())
        assertTrue(service.isNegativeStockAllowed())
        assertEquals("LIFO", service.getStockConsumptionStrategy())
        assertEquals("WHR-DEF", service.getDefaultWarehouseId())
    }
}
