openapi: 3.0.3
info:
  title: Customer Management API
  description: Customer relationship management for retail platform
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /customer/v1:
    post:
      summary: Create new customer
      description: Add a new customer with profile and contact information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_CustomerResponse'
        '400':
          description: Invalid request data
        '409':
          description: Customer already exists

  /customer/v1/list:
    get:
      summary: List customers
      description: Get paginated list of customers with search and filtering
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: search
          in: query
          description: Search in customer name, email, phone, or GST number
          schema:
            type: string
        - name: customer_type
          in: query
          schema:
            $ref: '#/components/schemas/CustomerType'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/CustomerStatus'
      responses:
        '200':
          description: Customer list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PagedCustomerResponse'

  /customer/v1/{customerId}:
    get:
      summary: Get customer details
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_CustomerResponse'
        '404':
          description: Customer not found

    put:
      summary: Update customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerRequest'
      responses:
        '200':
          description: Customer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_CustomerResponse'

    delete:
      summary: Delete customer
      description: Soft delete a customer (sets status to INACTIVE)
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted

  /customer/v1/{customerId}/transactions:
    get:
      summary: Get customer transaction history
      description: Get order and invoice history for a customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: from_date
          in: query
          schema:
            type: string
            format: date
        - name: to_date
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Transaction history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PagedCustomerTransactionResponse'

components:
  schemas:
    CreateCustomerRequest:
      type: object
      required:
        - name
        - customer_type
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        email:
          type: string
          format: email
        phone:
          type: string
          pattern: '^[+]?[1-9]\d{1,14}$'
        gst_number:
          type: string
          pattern: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'
        customer_type:
          $ref: '#/components/schemas/CustomerType'
        address:
          $ref: '#/components/schemas/AddressRequest'
        credit_limit:
          type: number
          format: decimal
          minimum: 0
        payment_terms:
          type: string
          maxLength: 100
        notes:
          type: string
          maxLength: 500

    UpdateCustomerRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        email:
          type: string
          format: email
        phone:
          type: string
          pattern: '^[+]?[1-9]\d{1,14}$'
        gst_number:
          type: string
          pattern: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'
        customer_type:
          $ref: '#/components/schemas/CustomerType'
        address:
          $ref: '#/components/schemas/AddressRequest'
        credit_limit:
          type: number
          format: decimal
          minimum: 0
        payment_terms:
          type: string
          maxLength: 100
        notes:
          type: string
          maxLength: 500
        status:
          $ref: '#/components/schemas/CustomerStatus'

    AddressRequest:
      type: object
      required:
        - line1
        - city
        - state
        - pincode
      properties:
        line1:
          type: string
          maxLength: 100
        line2:
          type: string
          maxLength: 100
        city:
          type: string
          maxLength: 50
        state:
          type: string
          maxLength: 50
        country:
          type: string
          maxLength: 50
          default: "India"
        pincode:
          type: string
          pattern: '^[0-9]{6}$'

    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        gst_number:
          type: string
        customer_type:
          $ref: '#/components/schemas/CustomerType'
        address:
          $ref: '#/components/schemas/AddressResponse'
        credit_limit:
          type: number
          format: decimal
        payment_terms:
          type: string
        notes:
          type: string
        status:
          $ref: '#/components/schemas/CustomerStatus'
        total_orders:
          type: integer
        total_invoices:
          type: integer
        outstanding_balance:
          type: number
          format: decimal
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AddressResponse:
      type: object
      properties:
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        pincode:
          type: string

    CustomerTransactionResponse:
      type: object
      properties:
        transaction_id:
          type: string
        transaction_type:
          type: string
          enum: [ORDER, INVOICE, PAYMENT]
        reference_number:
          type: string
        date:
          type: string
          format: date-time
        amount:
          type: number
          format: decimal
        status:
          type: string
        description:
          type: string

    CustomerType:
      type: string
      enum:
        - INDIVIDUAL
        - BUSINESS

    CustomerStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE

    ApiResponse_CustomerResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/CustomerResponse'

    ApiResponse_PagedCustomerResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PagedResponse_CustomerResponse'

    ApiResponse_PagedCustomerTransactionResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PagedResponse_CustomerTransactionResponse'

    ApiResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          $ref: '#/components/schemas/ErrorDetails'
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        trace_id:
          type: string

    ErrorDetails:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
        validation_errors:
          type: object
          additionalProperties:
            type: string
        module:
          type: string

    PagedResponse_CustomerResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CustomerResponse'
        page:
          type: integer
        size:
          type: integer
        total_elements:
          type: integer
        total_pages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

    PagedResponse_CustomerTransactionResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CustomerTransactionResponse'
        page:
          type: integer
        size:
          type: integer
        total_elements:
          type: integer
        total_pages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT