openapi: 3.0.3
info:
  title: Order Management API
  description: Order processing and management for retail platform
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /order/v1:
    post:
      summary: Create new order
      description: Create a new order with line items and pricing calculations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_OrderResponse'
        '400':
          description: Invalid request data
        '409':
          description: Insufficient inventory

  /order/v1/list:
    get:
      summary: List orders
      description: Get paginated list of orders with filtering
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/OrderStatus'
        - name: customer_id
          in: query
          schema:
            type: string
        - name: from_date
          in: query
          schema:
            type: string
            format: date
        - name: to_date
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Order list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PagedOrderResponse'

  /order/v1/{orderId}:
    get:
      summary: Get order details
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_OrderResponse'
        '404':
          description: Order not found

    put:
      summary: Update order
      description: Update order details (only for DRAFT status)
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderRequest'
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_OrderResponse'
        '409':
          description: Cannot update order in current status

  /order/v1/{orderId}/status:
    put:
      summary: Update order status
      description: Change order status with proper workflow validation
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderStatusRequest'
      responses:
        '200':
          description: Order status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_OrderResponse'
        '409':
          description: Invalid status transition

  /order/v1/{orderId}/convert-to-invoice:
    post:
      summary: Convert order to invoice
      description: Generate invoice from confirmed order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertToInvoiceRequest'
      responses:
        '201':
          description: Invoice created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_InvoiceResponse'
        '409':
          description: Cannot convert order in current status

components:
  schemas:
    CreateOrderRequest:
      type: object
      required:
        - line_items
      properties:
        customer_id:
          type: string
        line_items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderLineItemRequest'
        discount_amount:
          type: number
          format: decimal
          minimum: 0
          default: 0
        notes:
          type: string
          maxLength: 500

    UpdateOrderRequest:
      type: object
      properties:
        customer_id:
          type: string
        line_items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderLineItemRequest'
        discount_amount:
          type: number
          format: decimal
          minimum: 0
        notes:
          type: string
          maxLength: 500

    UpdateOrderStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'
        notes:
          type: string
          maxLength: 200

    ConvertToInvoiceRequest:
      type: object
      properties:
        due_date:
          type: string
          format: date
        payment_terms:
          type: string
          maxLength: 100
        invoice_notes:
          type: string
          maxLength: 500

    OrderLineItemRequest:
      type: object
      required:
        - product_id
        - quantity
      properties:
        product_id:
          type: string
        quantity:
          type: number
          format: decimal
          minimum: 0.01
        unit_price:
          type: number
          format: decimal
          minimum: 0
        discount_amount:
          type: number
          format: decimal
          minimum: 0
          default: 0

    OrderResponse:
      type: object
      properties:
        id:
          type: string
        order_number:
          type: string
        customer:
          $ref: '#/components/schemas/CustomerSummaryResponse'
        status:
          $ref: '#/components/schemas/OrderStatus'
        order_date:
          type: string
          format: date-time
        line_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderLineItemResponse'
        subtotal:
          type: number
          format: decimal
        tax_amount:
          type: number
          format: decimal
        discount_amount:
          type: number
          format: decimal
        total_amount:
          type: number
          format: decimal
        notes:
          type: string
        invoice_id:
          type: string
        created_by:
          $ref: '#/components/schemas/UserSummaryResponse'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    OrderLineItemResponse:
      type: object
      properties:
        id:
          type: string
        product:
          $ref: '#/components/schemas/ProductSummaryResponse'
        quantity:
          type: number
          format: decimal
        unit_price:
          type: number
          format: decimal
        tax_rate:
          type: number
          format: decimal
        line_total:
          type: number
          format: decimal
        tax_amount:
          type: number
          format: decimal
        discount_amount:
          type: number
          format: decimal

    CustomerSummaryResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string

    ProductSummaryResponse:
      type: object
      properties:
        id:
          type: string
        sku:
          type: string
        name:
          type: string
        unit_symbol:
          type: string

    UserSummaryResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    InvoiceResponse:
      type: object
      properties:
        id:
          type: string
        invoice_number:
          type: string
        order_id:
          type: string
        customer:
          $ref: '#/components/schemas/CustomerSummaryResponse'
        invoice_date:
          type: string
          format: date-time
        due_date:
          type: string
          format: date
        total_amount:
          type: number
          format: decimal
        paid_amount:
          type: number
          format: decimal
        balance_amount:
          type: number
          format: decimal
        status:
          $ref: '#/components/schemas/InvoiceStatus'

    OrderStatus:
      type: string
      enum:
        - DRAFT
        - CONFIRMED
        - PROCESSING
        - FULFILLED
        - CANCELLED
        - RETURNED

    InvoiceStatus:
      type: string
      enum:
        - DRAFT
        - SENT
        - PAID
        - PARTIAL_PAID
        - OVERDUE
        - CANCELLED

    ApiResponse_OrderResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/OrderResponse'

    ApiResponse_PagedOrderResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PagedResponse_OrderResponse'

    ApiResponse_InvoiceResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/InvoiceResponse'

    ApiResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          type: object
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        trace_id:
          type: string

    PagedResponse_OrderResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
        page:
          type: integer
        size:
          type: integer
        total_elements:
          type: integer
        total_pages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT