openapi: 3.0.3
info:
  title: Tax Code Management API
  description: Tax configuration and GST compliance for retail platform
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /tax-code/v1:
    post:
      summary: Create new tax code
      description: Create tax configuration with rate components for GST compliance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaxCodeRequest'
      responses:
        '201':
          description: Tax code created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TaxCodeResponse'
        '400':
          description: Invalid request data
        '409':
          description: Tax code name already exists

  /tax-code/v1/list:
    get:
      summary: List tax codes
      description: Get paginated list of tax codes with filtering
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: search
          in: query
          description: Search in tax code name or description
          schema:
            type: string
        - name: tax_type
          in: query
          schema:
            $ref: '#/components/schemas/TaxType'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/TaxStatus'
        - name: active_only
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Tax code list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PagedTaxCodeResponse'

  /tax-code/v1/{taxCodeId}:
    get:
      summary: Get tax code details
      parameters:
        - name: taxCodeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tax code details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TaxCodeResponse'
        '404':
          description: Tax code not found

    put:
      summary: Update tax code
      parameters:
        - name: taxCodeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaxCodeRequest'
      responses:
        '200':
          description: Tax code updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TaxCodeResponse'

    delete:
      summary: Delete tax code
      description: Soft delete a tax code (sets status to INACTIVE)
      parameters:
        - name: taxCodeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tax code deleted

  /tax-code/v1/{taxCodeId}/calculate:
    post:
      summary: Calculate tax for amount
      description: Calculate tax components for a given amount using this tax code
      parameters:
        - name: taxCodeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxCalculationRequest'
      responses:
        '200':
          description: Tax calculation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TaxCalculationResponse'

  /tax-code/v1/default:
    get:
      summary: Get default tax codes
      description: Get commonly used tax codes for quick setup
      responses:
        '200':
          description: Default tax codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_List_TaxCodeResponse'

    post:
      summary: Create default tax codes
      description: Create standard GST tax codes for Indian businesses
      responses:
        '201':
          description: Default tax codes created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_List_TaxCodeResponse'

components:
  schemas:
    CreateTaxCodeRequest:
      type: object
      required:
        - name
        - tax_type
        - rate
        - components
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: "e.g., 'GST 18%', 'IGST 5%'"
        description:
          type: string
          maxLength: 200
        tax_type:
          $ref: '#/components/schemas/TaxType'
        rate:
          type: number
          format: decimal
          minimum: 0
          maximum: 100
          description: "Total tax rate percentage"
        components:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/TaxComponentRequest'
        applicable_from:
          type: string
          format: date
        applicable_to:
          type: string
          format: date

    UpdateTaxCodeRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 200
        rate:
          type: number
          format: decimal
          minimum: 0
          maximum: 100
        components:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/TaxComponentRequest'
        applicable_from:
          type: string
          format: date
        applicable_to:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/TaxStatus'

    TaxComponentRequest:
      type: object
      required:
        - name
        - rate
      properties:
        name:
          type: string
          enum: [SGST, CGST, IGST, VAT, CESS]
          description: "Tax component type"
        rate:
          type: number
          format: decimal
          minimum: 0
          maximum: 100
        account_code:
          type: string
          maxLength: 20
          description: "Accounting system code"

    TaxCalculationRequest:
      type: object
      required:
        - taxable_amount
      properties:
        taxable_amount:
          type: number
          format: decimal
          minimum: 0
        is_interstate:
          type: boolean
          default: false
          description: "True for IGST, false for SGST+CGST"

    TaxCodeResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        tax_type:
          $ref: '#/components/schemas/TaxType'
        rate:
          type: number
          format: decimal
        components:
          type: array
          items:
            $ref: '#/components/schemas/TaxComponentResponse'
        applicable_from:
          type: string
          format: date
        applicable_to:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/TaxStatus'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    TaxComponentResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        rate:
          type: number
          format: decimal
        account_code:
          type: string

    TaxCalculationResponse:
      type: object
      properties:
        taxable_amount:
          type: number
          format: decimal
        total_tax_amount:
          type: number
          format: decimal
        total_amount:
          type: number
          format: decimal
        component_breakdown:
          type: array
          items:
            $ref: '#/components/schemas/TaxComponentCalculation'
        is_interstate:
          type: boolean

    TaxComponentCalculation:
      type: object
      properties:
        component_name:
          type: string
        rate:
          type: number
          format: decimal
        amount:
          type: number
          format: decimal

    TaxType:
      type: string
      enum:
        - GST
        - VAT
        - SERVICE_TAX
        - EXCISE
        - CUSTOM

    TaxStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE

    ApiResponse_TaxCodeResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TaxCodeResponse'

    ApiResponse_PagedTaxCodeResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PagedResponse_TaxCodeResponse'

    ApiResponse_TaxCalculationResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TaxCalculationResponse'

    ApiResponse_List_TaxCodeResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/TaxCodeResponse'

    ApiResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          $ref: '#/components/schemas/ErrorDetails'
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        trace_id:
          type: string

    ErrorDetails:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
        validation_errors:
          type: object
          additionalProperties:
            type: string
        module:
          type: string

    PagedResponse_TaxCodeResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/TaxCodeResponse'
        page:
          type: integer
        size:
          type: integer
        total_elements:
          type: integer
        total_pages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT