openapi: 3.0.3
info:
  title: Workspace Management API
  description: Multi-tenant workspace management for retail platform
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /workspace/v1:
    post:
      summary: Create new workspace
      description: Create a new workspace with business type configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspaceRequest'
      responses:
        '201':
          description: Workspace created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_WorkspaceResponse'
        '400':
          description: Invalid request data
        '409':
          description: Workspace slug already exists

  /workspace/v1/list:
    get:
      summary: List user workspaces
      description: Get all workspaces accessible to the authenticated user
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Workspace list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PagedWorkspaceResponse'

  /workspace/v1/{workspaceId}:
    get:
      summary: Get workspace details
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workspace details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_WorkspaceResponse'
        '404':
          description: Workspace not found

    put:
      summary: Update workspace
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkspaceRequest'
      responses:
        '200':
          description: Workspace updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_WorkspaceResponse'

  /workspace/v1/{workspaceId}/members:
    post:
      summary: Invite workspace member
      description: Send invitation to join workspace with specified role
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteMemberRequest'
      responses:
        '201':
          description: Invitation sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_InvitationResponse'

    get:
      summary: List workspace members
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Member list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_List_MemberResponse'

components:
  schemas:
    CreateWorkspaceRequest:
      type: object
      required:
        - name
        - slug
        - business_type
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 100
        slug:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 3
          maxLength: 50
        business_type:
          $ref: '#/components/schemas/BusinessType'
        description:
          type: string
          maxLength: 500
        enabled_modules:
          type: array
          items:
            $ref: '#/components/schemas/ModuleType'
          minItems: 1

    UpdateWorkspaceRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 100
        description:
          type: string
          maxLength: 500
        enabled_modules:
          type: array
          items:
            $ref: '#/components/schemas/ModuleType'

    InviteMemberRequest:
      type: object
      required:
        - email_or_phone
        - role
      properties:
        email_or_phone:
          type: string
        role:
          $ref: '#/components/schemas/WorkspaceRole'
        message:
          type: string
          maxLength: 200

    WorkspaceResponse:
      type: object
      properties:
        id:
          type: string
        slug:
          type: string
        name:
          type: string
        business_type:
          $ref: '#/components/schemas/BusinessType'
        description:
          type: string
        enabled_modules:
          type: array
          items:
            $ref: '#/components/schemas/ModuleType'
        member_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    MemberResponse:
      type: object
      properties:
        user_id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          $ref: '#/components/schemas/WorkspaceRole'
        joined_at:
          type: string
          format: date-time
        active:
          type: boolean

    InvitationResponse:
      type: object
      properties:
        invitation_id:
          type: string
        email_or_phone:
          type: string
        role:
          $ref: '#/components/schemas/WorkspaceRole'
        status:
          type: string
          enum: [PENDING, ACCEPTED, DECLINED, EXPIRED]
        sent_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time

    BusinessType:
      type: string
      enum:
        - RETAIL
        - WHOLESALE
        - MANUFACTURING
        - SERVICE
        - KIRANA
        - JEWELRY
        - HARDWARE

    ModuleType:
      type: string
      enum:
        - PRODUCT_MANAGEMENT
        - INVENTORY
        - ORDER_MANAGEMENT
        - INVOICE_GENERATION
        - CUSTOMER_MANAGEMENT
        - ANALYTICS
        - TALLY_INTEGRATION
        - NOTIFICATIONS

    WorkspaceRole:
      type: string
      enum:
        - ADMIN
        - MANAGER
        - STAFF

    ApiResponse_WorkspaceResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/WorkspaceResponse'

    ApiResponse_PagedWorkspaceResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/PagedResponse_WorkspaceResponse'

    ApiResponse_InvitationResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/InvitationResponse'

    ApiResponse_List_MemberResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/MemberResponse'

    ApiResponse:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          $ref: '#/components/schemas/ErrorDetails'
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        trace_id:
          type: string

    ErrorDetails:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
        validation_errors:
          type: object
          additionalProperties:
            type: string
        module:
          type: string

    PagedResponse_WorkspaceResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceResponse'
        page:
          type: integer
        size:
          type: integer
        total_elements:
          type: integer
        total_pages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT