package com.ampairs.inventory.domain.dto

import com.ampairs.inventory.domain.model.InventoryConfig
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.Size
import java.time.Instant

/**
 * Inventory Config Request DTO
 *
 * Used for creating and updating tenant inventory configuration.
 */
data class InventoryConfigRequest(

    // Auto Inventory Deduction
    var autoDeductOnOrder: Boolean = false,
    var allowManualOverride: Boolean = true,
    var blockOrdersWhenOutOfStock: Boolean = false,

    // Stock Consumption Strategy
    @field:Size(max = 20, message = "Stock consumption strategy must not exceed 20 characters")
    var stockConsumptionStrategy: String = "FIFO",  // FIFO, FEFO, LIFO, MANUAL

    // Tracking Defaults
    var enableBatchTrackingByDefault: Boolean = false,
    var enableSerialTrackingByDefault: Boolean = false,
    var enableExpiryTrackingByDefault: Boolean = false,

    // Alerts
    var enableLowStockAlerts: Boolean = true,
    var enableExpiryAlerts: Boolean = true,

    @field:Min(value = 1, message = "Expiry alert days must be at least 1")
    @field:Max(value = 365, message = "Expiry alert days must not exceed 365")
    var expiryAlertDays: Int = 30,

    var enableOverstockAlerts: Boolean = false,

    // Stock Policies
    var allowNegativeStock: Boolean = false,
    var requireApprovalForAdjustments: Boolean = false,

    // Multi-location
    var defaultWarehouseId: String? = null,

    // Ledger & Reporting
    var autoGenerateDailyLedger: Boolean = true,

    @field:Min(value = 0, message = "Ledger generation hour must be between 0 and 23")
    @field:Max(value = 23, message = "Ledger generation hour must be between 0 and 23")
    var ledgerGenerationHour: Int = 1,

    // Extensible Attributes
    var attributes: Map<String, Any>? = null
)

/**
 * Inventory Config Response DTO
 *
 * Used for API responses. Exposes all configuration fields.
 */
data class InventoryConfigResponse(
    val uid: String,

    // Auto Inventory Deduction
    val autoDeductOnOrder: Boolean,
    val allowManualOverride: Boolean,
    val blockOrdersWhenOutOfStock: Boolean,

    // Stock Consumption Strategy
    val stockConsumptionStrategy: String,

    // Tracking Defaults
    val enableBatchTrackingByDefault: Boolean,
    val enableSerialTrackingByDefault: Boolean,
    val enableExpiryTrackingByDefault: Boolean,

    // Alerts
    val enableLowStockAlerts: Boolean,
    val enableExpiryAlerts: Boolean,
    val expiryAlertDays: Int,
    val enableOverstockAlerts: Boolean,

    // Stock Policies
    val allowNegativeStock: Boolean,
    val requireApprovalForAdjustments: Boolean,

    // Multi-location
    val defaultWarehouseId: String?,

    // Ledger & Reporting
    val autoGenerateDailyLedger: Boolean,
    val ledgerGenerationHour: Int,

    // Extensible Attributes
    val attributes: Map<String, Any>?,

    // Timestamps
    val createdAt: Instant?,
    val updatedAt: Instant?
)

// Extension Functions for DTO Conversion

/**
 * Convert InventoryConfigRequest to InventoryConfig entity
 */
fun InventoryConfigRequest.toInventoryConfig(): InventoryConfig {
    val config = InventoryConfig()
    config.autoDeductOnOrder = this.autoDeductOnOrder
    config.allowManualOverride = this.allowManualOverride
    config.blockOrdersWhenOutOfStock = this.blockOrdersWhenOutOfStock
    config.stockConsumptionStrategy = this.stockConsumptionStrategy
    config.enableBatchTrackingByDefault = this.enableBatchTrackingByDefault
    config.enableSerialTrackingByDefault = this.enableSerialTrackingByDefault
    config.enableExpiryTrackingByDefault = this.enableExpiryTrackingByDefault
    config.enableLowStockAlerts = this.enableLowStockAlerts
    config.enableExpiryAlerts = this.enableExpiryAlerts
    config.expiryAlertDays = this.expiryAlertDays
    config.enableOverstockAlerts = this.enableOverstockAlerts
    config.allowNegativeStock = this.allowNegativeStock
    config.requireApprovalForAdjustments = this.requireApprovalForAdjustments
    config.defaultWarehouseId = this.defaultWarehouseId
    config.autoGenerateDailyLedger = this.autoGenerateDailyLedger
    config.ledgerGenerationHour = this.ledgerGenerationHour
    config.attributes = this.attributes
    return config
}

/**
 * Convert InventoryConfig entity to InventoryConfigResponse DTO
 */
fun InventoryConfig.asInventoryConfigResponse(): InventoryConfigResponse {
    return InventoryConfigResponse(
        uid = this.uid,
        autoDeductOnOrder = this.autoDeductOnOrder,
        allowManualOverride = this.allowManualOverride,
        blockOrdersWhenOutOfStock = this.blockOrdersWhenOutOfStock,
        stockConsumptionStrategy = this.stockConsumptionStrategy,
        enableBatchTrackingByDefault = this.enableBatchTrackingByDefault,
        enableSerialTrackingByDefault = this.enableSerialTrackingByDefault,
        enableExpiryTrackingByDefault = this.enableExpiryTrackingByDefault,
        enableLowStockAlerts = this.enableLowStockAlerts,
        enableExpiryAlerts = this.enableExpiryAlerts,
        expiryAlertDays = this.expiryAlertDays,
        enableOverstockAlerts = this.enableOverstockAlerts,
        allowNegativeStock = this.allowNegativeStock,
        requireApprovalForAdjustments = this.requireApprovalForAdjustments,
        defaultWarehouseId = this.defaultWarehouseId,
        autoGenerateDailyLedger = this.autoGenerateDailyLedger,
        ledgerGenerationHour = this.ledgerGenerationHour,
        attributes = this.attributes,
        createdAt = this.createdAt,
        updatedAt = this.updatedAt
    )
}
