rootProject.name = "ampairs"

include("core")
include("notification")
include("auth")
include("workspace")
include("form")
include("event")
include("product")
include("business")
include("customer")
include("order")
include("invoice")
include("tax")
include("ampairs_service")
