-- MySQL counterpart of postgresql/V1.0.65.
CREATE TABLE ecom_order (
    id                      BIGINT NOT NULL AUTO_INCREMENT,
    uid                     VARCHAR(200) NOT NULL,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ecom_order_ref          VARCHAR(50)  NOT NULL,
    storefront_id           VARCHAR(200) NOT NULL,
    workspace_id            VARCHAR(200) NOT NULL,
    customer_id             VARCHAR(200) NOT NULL,
    customer_name           VARCHAR(255) NOT NULL,
    customer_email          VARCHAR(320) NOT NULL,
    customer_phone          VARCHAR(20),
    delivery_address        JSON         NOT NULL,
    status                  VARCHAR(30)  NOT NULL DEFAULT 'PLACED',
    management_order_ref    VARCHAR(255),
    subtotal                DECIMAL(19,4) NOT NULL,
    total_amount            DECIMAL(19,4) NOT NULL,
    notes                   TEXT,
    placed_at               TIMESTAMP    NOT NULL,
    confirmed_at            TIMESTAMP    NULL,
    merchant_reviewed_at    TIMESTAMP    NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX uq_ecom_order_uid (uid),
    UNIQUE INDEX uq_ecom_order_ref (ecom_order_ref),
    INDEX idx_ecom_order_storefront (storefront_id),
    INDEX idx_ecom_order_customer   (customer_id),
    INDEX idx_ecom_order_workspace  (workspace_id),
    INDEX idx_ecom_order_status     (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ecom_order_line_item (
    id                      BIGINT NOT NULL AUTO_INCREMENT,
    uid                     VARCHAR(200) NOT NULL,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ecom_order_id           VARCHAR(200) NOT NULL,
    listed_product_id       VARCHAR(200) NOT NULL,
    management_product_id   VARCHAR(200) NOT NULL,
    product_name            VARCHAR(255) NOT NULL,
    unit_price              DECIMAL(19,4) NOT NULL,
    quantity_ordered        INT          NOT NULL,
    quantity_confirmed      INT,
    line_total              DECIMAL(19,4) NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ORDERED',
    shipment_group          VARCHAR(100),
    PRIMARY KEY (id),
    UNIQUE INDEX uq_ecom_order_line_item_uid (uid),
    INDEX idx_ecom_order_line_item_order (ecom_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
