-- MySQL counterpart of postgresql/V1.0.63 (JSONB→JSON; JSON DEFAULT requires expression syntax).
CREATE TABLE ecom_listed_product (
    id                      BIGINT NOT NULL AUTO_INCREMENT,
    uid                     VARCHAR(200) NOT NULL,
    owner_id                VARCHAR(200),
    ref_id                  VARCHAR(255),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    storefront_id           VARCHAR(200) NOT NULL,
    management_product_id   VARCHAR(200) NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    description             TEXT,
    image_urls              JSON         NOT NULL DEFAULT (JSON_ARRAY()),
    brand                   VARCHAR(255),
    category                VARCHAR(255),
    subcategory             VARCHAR(255),
    price                   DECIMAL(19,4) NOT NULL,
    stock_quantity          INT          NOT NULL DEFAULT 0,
    stock_status            VARCHAR(20)  NOT NULL DEFAULT 'OUT_OF_STOCK',
    is_visible              BOOLEAN      NOT NULL DEFAULT TRUE,
    last_synced_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX uq_ecom_listed_product_uid (uid),
    UNIQUE INDEX uq_ecom_product_storefront (storefront_id, management_product_id),
    INDEX idx_ecom_product_storefront   (storefront_id),
    INDEX idx_ecom_product_management   (management_product_id),
    INDEX idx_ecom_product_visible      (storefront_id, is_visible),
    INDEX idx_ecom_product_stock_status (storefront_id, stock_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
