package com.ampairs.inventory.service

import com.ampairs.inventory.domain.model.InventoryConfig
import com.ampairs.inventory.repository.InventoryConfigRepository
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional

/**
 * Inventory Configuration Service
 *
 * Business logic layer for inventory configuration management.
 * Handles tenant-level inventory settings.
 *
 * Key Responsibilities:
 * - Get or create default configuration
 * - Update configuration settings
 * - Provide configuration for transaction processing
 */
@Service
class InventoryConfigService @Autowired constructor(
    private val inventoryConfigRepository: InventoryConfigRepository
) {

    /**
     * Get configuration for current tenant
     *
     * If configuration doesn't exist, creates default configuration
     *
     * @return InventoryConfig
     */
    @Transactional
    fun getOrCreateConfig(): InventoryConfig {
        return inventoryConfigRepository.findFirstByOrderByCreatedAtDesc()
            ?: createDefaultConfig()
    }

    /**
     * Get configuration by UID
     *
     * @param uid Configuration UID
     * @return InventoryConfig if found, null otherwise
     */
    fun getConfigByUid(uid: String): InventoryConfig? {
        return inventoryConfigRepository.findByUid(uid)
    }

    /**
     * Update configuration
     *
     * @param uid Configuration UID
     * @param updates InventoryConfig with updated fields
     * @return Updated configuration
     * @throws IllegalArgumentException if configuration not found
     */
    @Transactional
    fun updateConfig(uid: String, updates: InventoryConfig): InventoryConfig {
        val existing = getConfigByUid(uid)
            ?: throw IllegalArgumentException("Configuration not found: $uid")

        // Update all fields
        existing.autoDeductOnOrder = updates.autoDeductOnOrder
        existing.allowManualOverride = updates.allowManualOverride
        existing.blockOrdersWhenOutOfStock = updates.blockOrdersWhenOutOfStock
        existing.stockConsumptionStrategy = updates.stockConsumptionStrategy
        existing.enableBatchTrackingByDefault = updates.enableBatchTrackingByDefault
        existing.enableSerialTrackingByDefault = updates.enableSerialTrackingByDefault
        existing.enableExpiryTrackingByDefault = updates.enableExpiryTrackingByDefault
        existing.enableLowStockAlerts = updates.enableLowStockAlerts
        existing.enableExpiryAlerts = updates.enableExpiryAlerts
        existing.expiryAlertDays = updates.expiryAlertDays
        existing.enableOverstockAlerts = updates.enableOverstockAlerts
        existing.allowNegativeStock = updates.allowNegativeStock
        existing.requireApprovalForAdjustments = updates.requireApprovalForAdjustments
        existing.defaultWarehouseId = updates.defaultWarehouseId
        existing.autoGenerateDailyLedger = updates.autoGenerateDailyLedger
        existing.ledgerGenerationHour = updates.ledgerGenerationHour
        existing.attributes = updates.attributes

        return inventoryConfigRepository.save(existing)
    }

    /**
     * Create default configuration for tenant
     *
     * @return Created default configuration
     */
    @Transactional
    private fun createDefaultConfig(): InventoryConfig {
        val config = InventoryConfig()
        // Default values are already set in entity
        return inventoryConfigRepository.save(config)
    }

    /**
     * Check if auto inventory deduction is enabled
     *
     * @return true if enabled, false otherwise
     */
    fun isAutoDeductEnabled(): Boolean {
        val config = getOrCreateConfig()
        return config.autoDeductOnOrder
    }

    /**
     * Check if manual override is allowed
     *
     * @return true if allowed, false otherwise
     */
    fun isManualOverrideAllowed(): Boolean {
        val config = getOrCreateConfig()
        return config.allowManualOverride
    }

    /**
     * Check if negative stock is allowed
     *
     * @return true if allowed, false otherwise
     */
    fun isNegativeStockAllowed(): Boolean {
        val config = getOrCreateConfig()
        return config.allowNegativeStock
    }

    /**
     * Get stock consumption strategy
     *
     * @return Stock consumption strategy (FIFO, FEFO, LIFO, MANUAL)
     */
    fun getStockConsumptionStrategy(): String {
        val config = getOrCreateConfig()
        return config.stockConsumptionStrategy
    }

    /**
     * Get default warehouse ID if configured
     *
     * @return Default warehouse UID or null
     */
    fun getDefaultWarehouseId(): String? {
        val config = getOrCreateConfig()
        return config.defaultWarehouseId
    }
}
